### PR TITLE
changing application name from ojs2 to ojs3 #1839

### PR DESCRIPTION
**Pull request by kaschioudi**
cf, https://github.com/pkp/pkp-lib/issues/1839

### CODE REVIEW

**Comment by asmecher** [comment]
@kaschioudi, have you checked to see what the impact of this change is on already-existing installations of OJS (which will refer to `ojs2` in the database)?

**Comment by kaschioudi** [comment]
you're right. it actually brakes existing ojs3 installs. I get the error below.  
`Fatal error:  Call to a member function getVersionString() on a non-object in /www/pkp/ojs3/lib/pkp/classes/template/PKPTemplateManager.inc.php on line 230`

**Comment by asmecher** [comment]
I'm not sure it'll be possible to update this in the upgrade scripts, because those will want to check what version you're using. It might be best just to leave this as is -- it's a back-end issue and not displayed to the user anywhere.

**Comment by kaschioudi** [comment]
Alright. Please disregard my pull request.

**Comment by asmecher** [comment]
OK! It'd be nice to update this, but not a big deal. I'll see if I can think of something.

**Pull request closed without merging**
