### PR TITLE
Latest pl_PL translation for OJS 3.1.2

### PR DESCRIPTION
**Pull request by szmigieldesign**
Latest pl_PL XML files from OJS 3.1.2.1 to be merged with Weblate

### CODE REVIEW

**Comment by asmecher** [comment]
@szmigieldesign, thanks! One request: this PR appears to have a lot of submodule updates in it that might not be necessary. Are there updated pl_PL translations in any of the updated submodules (besides `lib/pkp`)? If not, could you remove those updates from the pull request?

**Comment by szmigieldesign** [comment]
@asmecher I've no idea where do they come from. I've only updated the XML files but somehow git adds -dirty to folders and I can't discard it. Any ideas? Or perhaps can you just sync XML files?

**Comment by asmecher** [comment]
@szmigieldesign, did you do a `git add -u` before `git commit`? That would explain it. It won't just add updated files, it'll also add modified submodules. Submodules are tricky :)

It's a pain to remove these from a commit -- I'll see if I can manually merge this via `patch` instead.

**Comment by asmecher** [comment]
Manually merged to `stable-3_1_2`: https://github.com/pkp/ojs/commit/04f90c3d68bf5751a9d937519c23acccf204b8b8

**Comment by asmecher** [comment]
Ported to `master`: https://github.com/pkp/ojs/commit/91c5ee029ae1a92afb5023e9adc2145c509d9074

**Comment by asmecher** [comment]
Also updated `quickSubmit` and `customHeader` plugins, both `stable-3_1_2` and `master` branch. I think that's everything -- thanks, @szmigieldesign! I'll update Weblate shortly, so future updates can come that way.

**Pull request closed without merging**
