### PR TITLE
New Serbian locales for OJS 3.x

### PR DESCRIPTION
**Pull request by vedranvucic**
new translated locale files

### CODE REVIEW

**Comment by mtub** [comment]
This is for pkp/pkp-lib#2337

**Comment by asmecher** [comment]
There are some XML validation problems here -- see e.g. https://travis-ci.org/pkp/ojs/jobs/209839293

**Comment by mtub** [comment]
Fixed the XML errors (cc: @vedranvucic). Mind having another quick look, @asmecher ?

**Comment by vedranvucic** [comment]
Which files I should check?

**Comment by mtub** [comment]
Hi @vedranvucic , nothing to check for you :) - there where two errors in both of the variants with XML tags not closed, but I fixed those already (e1a4621, 7c7785d, 968e28f,  94f9b62). I was just asking Alec to have another look because this is a huge commit, but the automatic test has gone through without problems.

**Comment by bozana** [comment]
@asmecher will be less available for a few weeks, so I can take a look at this...

**Comment by bozana** [comment]
@vedranvucic, why is the file locale/sr_RS@cyrillic/emailTemplates.xml  not in Cyrillic?

**Comment by bozana** [comment]
@mtub, @vedranvucic, what about the current sr_SR folder? Should it be removed?

**Comment by mtub** [comment]
Hi @bozana, let me take care of the old folder and of the locale registry file. will send a PR.

**Comment by vedranvucic** [comment]
Hello, Mail templates are usually heavily edited by editorial boards so we left that file untranslated since we do not see purpose of translating something that will be radically changed anyway.

**Comment by vedranvucic** [comment]
The current sr_RS loacle should be replaced and new locales will take place instead since there are two scripts in Serbian language.

**Pull request merged**
