### PR TITLE
Update submission.xml

### PR DESCRIPTION
**Pull request by marcbria**
Error in the original en_US files.

### CODE REVIEW

**Comment by asmecher** [comment]
That should be `unavailable`, not `unvailable` -- but thanks for spotting, I'll fix it!

**Comment by asmecher** [comment]
https://github.com/pkp/ojs/commit/f95814e4f2286d425fcbeae7d0aaf796da910ad7

**Comment by marcbria** [comment]
Three chars and one was missing... Great contribution. :-D
Sorry Alec, you know about my poor English skills.

**Comment by asmecher** [comment]
You found a typo and now it's fixed, don't worry about the route we took to get there :)

**Pull request closed without merging**
