### PR TITLE
Locale update for OJS 2.4.8-1

### PR DESCRIPTION
**Pull request by mtub**
Sorry, @asmecher - this may look much, but I think it's okay. Cherry-picked (and checked) the locale updates that `ojs-dev-2_4` had received since the release of OJS 2.4.8

pkp/pkp-lib#1560

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @mtub! A couple quick notes:

- There are some files here with DOS line endings (not a big deal but I favour UNIX-style endings for consistency)
- There are very few newly-added files among the updates; is this what you would expect from the updates?

**Comment by mtub** [comment]
hey @asmecher,

a) well - then let's get rid of them, once and for all (before porting to OJS3). will update this PR (and prepare a cherry-pick for ojs-dev-2_4)

b) Yes, there's not so much new. This is just what has been updated since the OJS 2.4.8 release.

**Comment by asmecher** [comment]
*whew*

**Comment by mtub** [comment]
ah, you've merged this already… will commit line ending changes in a new PR

**Comment by asmecher** [comment]
Yes, and I'll cherry-pick it to either `ojs-stable-2_4_8` or `ojs-dev-2_4` depending on where you send it.

**Pull request merged**
