### PR TITLE
registrer form locale error in privacyConsent

### PR DESCRIPTION
**Pull request by vasmedv**
in version ojs-3.1.1-4.tar.gz  need to be 
message key="user.register.form.emailConsent" and message key="user.register.form.privacyConsent"
instead of 
message key="user.register.form.emailConsentAllContexts" and 
message key="user.register.form.privacyConsentThisContext"

### CODE REVIEW

**Comment by mtub** [comment]
Hi @vasmedv, I am not sure if I understand your message correctly. You have suggested to update the Russian translation to the other key names. The translation is correct as it mirrors the en_US locale version.

I guess you are referring to the forms requesting other keys. So instead of updating all locale files I'd rather have @NateWr have a look at pkp-lib's `userRegister.tpl`. Nate, could you check this?

**Comment by vasmedv** [comment]
> I guess you are referring to the forms requesting other keys. So instead of updating all locale files I'd rather have @NateWr have a look at pkp-lib's `userRegister.tpl`. Nate, could you check this?

Yes, i think this problem could be better solved by editing pkp-lib. Question is why key names were changed? Or, i seem to understand, you want new key names put into pkp-lib.

**Comment by NateWr** [comment]
In https://github.com/pkp/pkp-lib/commit/15c1290474b5597a0cb0e005d2ee313eaf139181 the site-wide registration form was changed. The privacy statement confirmation was placed alongside each journal that the user registers for.

You will find `user.register.form.privacyConsentThisContext` used in `lib/pkp/templates/frontend/components/registrationFormContexts.tpl`: https://github.com/pkp/pkp-lib/commit/15c1290474b5597a0cb0e005d2ee313eaf139181#diff-ff1a3fdffd5316919720104c321e0519R74

The email opt-in is site-wide and the language used does not indicate one or all journals. So `user.register.form.emailConsentAllContexts` is now obsolete and probably should be removed.

**Comment by mtub** [comment]
Ok, closing this. @NateWr, should I go ahead and remove `user.register.form.emailConsentAllContexts` from the locale files?

**Comment by NateWr** [comment]
If you can that'd be great. Otherwise you can file an issue and assign it to me.

**Comment by vasmedv** [comment]
Still there is use of key `user.register.form.privacyConsent` in `lib/pkp/templates/frontend/pages/userRegister.tpl`. What can you tell about it?

**Comment by NateWr** [comment]
Hi @vasmedv, can you describe in more detail the issue that you're having?

**Comment by vasmedv** [comment]
in `lib/pkp/templates/frontend/pages/userRegister.tpl` there are those strings:
`{* Require the user to agree to the terms of the privacy policy *}
{if $siteWidePrivacyStatement}
	<div class="fields">
		<div class="optin optin-privacy">
			<label>
				<input type="checkbox" name="privacyConsent[{$smarty.const.CONTEXT_ID_NON
				{capture assign="privacyUrl"}{url router=$smarty.const.ROUTE_PAGE page="a
			{translate key="user.register.form.privacyConsent" privacyUrl=$privacyUrl
			</label>
		</div>
	</div>
{/if}`
Then i suppose the key `user.register.form.privacyConsentThisContext` is not enough for thanslating the data of agreement to the terms of the privacy policy. And the key `user.register.form.privacyConsentThisContext` is necessary. Now in our journal we use only english locale. But in previous year we tested OJS in russian locale and there was a display problem with those keys.

**Comment by NateWr** [comment]
@vasmedv It looks like the Russian translation has been updated with that key now and it should be available in 3.1.2:

https://github.com/pkp/pkp-lib/blob/stable-3_1_2/locale/ru_RU/user.xml#L111

**Pull request closed without merging**
