### PR TITLE
Authors list on reviewers page

### PR DESCRIPTION
**Pull request by MrRob100**
ui-library: https://github.com/pkp/ui-library/pull/287
pkp-lib: https://github.com/pkp/pkp-lib/pull/9288

### CODE REVIEW

**Comment by jardakotesovec** [comment]
@asmecher Trickiest part here will be couple of new locale keys - any suggestion how to go about them? Maybe separate PR for next 3.4 version just to include strings?

**Comment by asmecher** [comment]
@jardakotesovec Agreed, I could merge a PR to add the new locale keys immediately, then wait to merge the feature addition until the translators have had a bit of time to catch up.

**Comment by MrRob100** [comment]
@asmecher this PR https://github.com/pkp/pkp-lib/pull/9495 has just the locale key changes

**Comment by asmecher** [comment]
@MrRob100, thanks, I've merged the locale file changes. Is there an issue filed for this, or just pull requests so far?

**Comment by MrRob100** [comment]
Just a pull request. For future reference should there be an issue for this? Even if the pull requests relate to a feature rather than an actually ‘issue’? And each of the pull requests for this feature link to that issue?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by asmecher** [comment]
@MrRob100, yes, please do create an issue; we use those to coordinate changelogs, feature lists, and in particular to connect things together when there are PRs to multiple repositories/branches.

**Comment by asmecher** [comment]
@MrRob100, I've filed an issue to go along with this -- it makes tracking easier when PRs go to many repositories. Can you add a high-level description of the feature over on https://github.com/pkp/pkp-lib/issues/9756? Thanks!

**Comment by asmecher** [comment]
Cherry-picked https://github.com/pkp/ojs/pull/4061/commits/31f1f45de735a5618b29e065ffb4050b353b98fd manually

**Pull request closed without merging**
