### PR TITLE
Reload workflow after decline decision #5757

### PR DESCRIPTION
**Pull request by ajnyga**

### CODE REVIEW

**Comment by ajnyga** [comment]
@asmecher single test failed here, can you restart...

**Comment by asmecher** [comment]
Restarted!

**Comment by ajnyga** [comment]
so the tests worked ok, but now it says that there is a conflict...

**Comment by asmecher** [comment]
@ajnyga, since the OJS PR is just the submodule update for testing purposes, you can go ahead and close it -- someone else will come along and bump the submodule up to date soon -- and merge the pkp-lib PR whenever you're ready.

**Comment by ajnyga** [comment]
I don't think I can merge a pkp-lib pr

**Comment by asmecher** [comment]
Is it ready for merging (and possibly cherry-picking to `stable-3_2_0`)? If so, let me know and I'll go ahead.

**Comment by ajnyga** [comment]
should be ready

**Comment by ajnyga** [comment]
this probably did not get merged yet?

**Comment by asmecher** [comment]
You're right; this wasn't scheduled against the 3.2.0-3 milestone so I missed it. Merged https://github.com/pkp/pkp-lib/pull/5758 and back-ported to `stable-3_2_0`.

**Pull request closed without merging**
