### PR TITLE
pkp/pkp-lib#1838 Automatic emails for open access/subscription trigge…

### PR DESCRIPTION
**Pull request by mfelczak**
…red post-install

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @mfelczak -- this will also need the queries added to the DB upgrade script.

**Comment by asmecher** [comment]
Thanks, @mfelczak -- one more addition :) The queries should also go into `dbscripts/xml/upgrade/3.0.0_update.xml` for the sake of people using `ojs-stable-3_0_0`. When I merge I'll cherry-pick forward to master as well.

**Comment by mfelczak** [comment]
Thanks @asmecher, I've added `dbscripts/xml/upgrade/3.0.0_update.xml` to the PR

**Comment by mfelczak** [comment]
@asmecher, also removed the Acron crontab setting from the DB which includes the extra open access + subscription tasks. The crontab setting will then be automatically generated with correct tasks post install/upgrade.

**Comment by mfelczak** [comment]
Nevermind, I see that the crontab setting is always regenerated post install/upgrade, no need to remove the setting from the DB.

**Pull request merged**
