### PR TITLE
Provides a possibility to import references from a XML submission pkp/pkp-lib#4195

### PR DESCRIPTION
**Pull request by JhonathanLepidus**
Now the native import/export plugin can recognize the citations from submissions.

### CODE REVIEW

**Comment by JhonathanLepidus** [comment]
The submodule linking in commit https://github.com/pkp/ojs/pull/2654/commits/13e97a4de61bfb390d1644fecf8ef83f57774dc5 should not be considered, since it's related to ours repositories.

**Comment by asmecher** [comment]
This looks good, @JhonathanLepidus, but appears to only address the export side of things; do you have code (or plans to write code) for import? I prefer to keep this symmetrical.

**Comment by asmecher** [comment]
My mistake, @JhonathanLepidus, I see that this is in the other PR: https://github.com/pkp/pkp-lib/pull/5566

**Comment by asmecher** [comment]
Cherry-picked:
- 666f1ac6ed66bd09e112e2824e5f50c5f3e6031a
- 33560b8844e99d68535b2fed1ae12bb47c9fa49b
- 60e14f4318d49ddb25ca4604dab7fe1a975f06d2
- 9b6e078e12cf4fa7e83897c2f8d8b4c069beca7c
...to `stable-3_1_2`!

**Pull request closed without merging**
