### PR TITLE
Partially update pt_BR translation

### PR DESCRIPTION
**Pull request by leofontenelle**

### CODE REVIEW

**Comment by leofontenelle** [comment]
I can't see from the Travis CI log in what way my commit would be breaking the build.

**Comment by asmecher** [comment]
@leofontenelle, the Travis build appears to have worked just fine!

**Comment by mtub** [comment]
Sometimes Travis CI just runs into problems not caused by your changes. I had it run again and now it doesn't show any errors ;) - thanks for contributing, will review and get back to you.

**Comment by mtub** [comment]
Mentioning @ronniebrito, in case you want to have a look. I will merge this after my checks, but feel free to comment or update later on if needed.

**Pull request merged**
