### PR TITLE
some missing strings Spanish translation

### PR DESCRIPTION
**Pull request by t4x0n**
some missing strings, and the new legacy strings section (I followed the guidelines)

### CODE REVIEW

**Comment by t4x0n** [comment]
@marcbria take a look to this PR please

**Comment by t4x0n** [comment]
Hi @marcbria, the next release is pretty soon. This strings and others are missed yet; I hope you could check this pull request in order to improve Spanish translation.  Thanks!

**Comment by marcbria** [comment]
@t4x0n my translator is stucked with this chains...
I will suggest him comment case by case in you file.

@mtub do we have a release soon? I was not aware of this.

**Comment by t4x0n** [comment]
@marcbria this is the next release and is close to 100% https://github.com/pkp/pkp-lib/milestone/24

**Comment by marcbria** [comment]
Thanks @t4x0n to remember we have this issue open.
Tomorrow I will talk with jordi and we will try to take a decision.

**Comment by marcbria** [comment]
@t4x0n finally we reviewed your PR. Changes over your changes.
Thanks for your work.

@mtub , from us, all ready to merge.

**Comment by t4x0n** [comment]
@mtub just for remember to merge

**Comment by asmecher** [comment]
Hi @t4x0n -- thanks! Marco's unavailable for a little while, so I'm covering reviews/merges in the meantime.

**Pull request merged**
