### PR TITLE
Prepare COUNTER plugin for SUSHI-Lite

### PR DESCRIPTION
**Pull request by ctgraham**
Some cleanup work in preparation for a retooling of the COUNTER plugin.
* Create and use a templates folder for a bit of orgainzation
* fix the mixed usage of ReportPlugin::report() parameterization
* Correct existing report release number in locale files.
* ~~Create classes folder for additional organization~~
* ~~Migrate legacy JR1 (R3) functionality to its own class~~
* Clarify relationship of Counter plugin to COUNTER compliance
* Addresses pkp/pkp-lib#274

### CODE REVIEW

**Comment by ctgraham** [comment]
This PR needs cleanup.  Will force update the branch with a better tree.

**Comment by ctgraham** [comment]
New tree to resolve merge conflicts.  Defers the creation of the "classes" folder reorganization and migrating the legacy JR1(R3) to a new class.

**Comment by ctgraham** [comment]
@beghelli, can you review for pull into dev-2_4?  I'm starting to work on the next step of the Sushi implementation.

**Comment by beghelli** [comment]
@ctgraham, sure, I have to finish a work here today, reviewing it as soon as I finish this. Thanks for this work.

**Comment by beghelli** [comment]
Just two comments Clinton. Thanks a lot! :)

**Comment by ctgraham** [comment]
Added anonymous as a locale key and squashed the commits.

**Comment by ctgraham** [comment]
@beghelli , back to you.

**Comment by beghelli** [comment]
@ctgraham , will merge after the test build if finished. Thanks.

**Pull request merged**
