### PR TITLE
Updating some Arabic locale files before June, 15

### PR DESCRIPTION
**Pull request by vormia**

### CODE REVIEW

**Comment by asmecher** [comment]
Merging and cherry-picking to `stable-3_2_1` -- thanks, @vormia! Have you tried the Weblate-based translation toolset at https://translate.pkp.sfu.ca?

**Comment by vormia** [comment]
@asmecher,
Thanks for referring to this magnificent tool. I signed in and participated in the translations, but I can only suggest updates, not save them!... You may find me there having many suggestions regarding ar_IQ locale.

**Comment by asmecher** [comment]
@vormia, have you signed the Contributor License Agreement? Unfortunately it's a bit of a pain -- it's necessary to agree to it for each component -- but I haven't been able to find out a way to make this global yet.

**Comment by vormia** [comment]
Hi @asmecher, 
After exploring here and there... Everything is **done**.

**Comment by asmecher** [comment]
@vormia, excellent news, thanks! I'll make sure this goes out with version 3.2.1.

**Pull request merged**
