### PR TITLE
Update manager.xml

### PR DESCRIPTION
**Pull request by awangga**
update language

### CODE REVIEW

**Comment by mtub** [comment]
Thanks, @awangga. Is this one-line change everything you wanted to contribute? As you might have noticed, the Indonesian locale is really incomplete, and there is still much English text in the locale files. Are you planning to work some more on the translation? If so, you can update this pull request by adding more commits to this branch. In this case, you should let me know when you are done, and I can review and merge your additions.

If you don't want to add anything else, please let me know and I will merge this.

Thanks,
Marco

**Comment by awangga** [comment]
thankyou @mtub i will do continue my translation from english into indonesian

**Comment by mtub** [comment]
Are you aware of the work @mohammadrizki  is doing? See #1272 ...

**Comment by mtub** [comment]
Merging this, please file a new pull request for future updates.

**Pull request merged**
