### PR TITLE
[OJS] #5801 remove duplicates and referenced submission from rec…

### PR DESCRIPTION
**Pull request by Vitaliy-1**
…ommend by author results

1. Not sure why array_unique was used on submissions; can this array contain duplicate values?
2. On line 89 array_filter is used. According to the [example](https://www.php.net/manual/en/function.array-filter.php#example-6248), I can't figure out situation when it may be useful. Left it as is but can remove if necessary.

### CODE REVIEW

**Comment by asmecher** [comment]
@Vitaliy-1, I think `array_unique` is necessary so that submissions with multiple publications don't get fetched twice.

The `array_filter` call was added a part of a fix for pkp/pkp-lib#5683; it removes entries from the array that correspond to publications that aren't published.

**Comment by asmecher** [comment]
Just points for style, but I'd suggest using a lambda function in the existing `array_filter` call to kill two birds with one stone -- remove `null` entries, and the current submission ID.

**Comment by Vitaliy-1** [comment]
Thanks!

I suspected that it may be related to another issue, although I can't reproduce it. Did you mean something like in the additional commit? Also, I don't understand why some checks are failing.

**Comment by asmecher** [comment]
@Vitaliy-1, yes, the additional commit looks good. Don't worry about the tests -- they've been a little less reliable lately; I'll try to take a look. But that's not related to this PR.

**Comment by asmecher** [comment]
In other words, if you're ready, please go ahead and merge!

**Comment by Vitaliy-1** [comment]
@asmecher, I'm afraid I don't have write access to ojs repo, only to shared library.

**Comment by asmecher** [comment]
@Vitaliy-1, I've just sent you an invite!

**Pull request merged**
