### PR TITLE
Reminder template

### PR DESCRIPTION
**Pull request by geocode64**
Resolves a bug where users were erroneously being sent a REVIEW_REMIND_AUTO email template instead of a automated review request reminder (of which a template did not exist).

This occurs when the setting under Journal Management > Journal Setup >  Step 2 > Reviewer Reminders is set:

image

Logic has been added to check for this setting and also two new templates were added (REVIEW_REQUEST_REMIND_AUTO and REVIEW_REQUEST_REMIND_AUTO_ONECLICK)

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @geocode64 -- I haven't considered this a bug so much as an oft-requested improvement over an annoying sharing of email templates. See e.g. forum.pkp.sfu.ca/t/different-templates-for-automated-review-request-reminder-and-automated-review-reminder for details.

I'm hesitant to merge this as is, though, because we don't expect to do a formal translation round for OJS 2.4.8 and without translations of that template blank messages will be sent out.

One option would be to duplicate the existing (sub-optimal) text for all languages for which we don't have improved translations. That would echo the current behavior, but permit translations to resolve the issue by updating the templates.

**Comment by geocode64** [comment]
@asmecher I've created two new templates for each of the locales that had an emailTemplates.xml file by duplicating the REVIEW_REQUEST and REVIEW_REQUEST_ONECLICK files as you suggested.

**Comment by ctgraham** [comment]
+1ish to duplicating the existing language texts into new emails.  Making site-by-site translation fixes now and reconciling new official translations later will be unfortunate, but the current confusion generated by using the same emails for all cases needs attention.

**Comment by asmecher** [comment]
Thanks, @geocode64. I don't see the template updates for the other locales; did you forget to push to the PR?

**Comment by geocode64** [comment]
Was having a few git issues at our end, all sorted now.

If adding new email templates is a bit messy, what about just using the existing REVIEW_REQUEST and REVIEW_REQUEST_ONECLICK templates for the automated review request reminder emails?

**Comment by asmecher** [comment]
Thanks, @geocode64, that's fine.

I'm going to merge this and port to ojs-dev-2_4, and also add an upgrade script chunk to install the new templates on upgrade.

Your contribution is much appreciated!

**Comment by asmecher** [comment]
Created an issue and added upgrade scripts to insert the template:
https://github.com/pkp/pkp-lib/issues/1054

**Comment by bozana** [comment]
@asmecher, does the {weekLaterDate} in the new auto reviewer reminder email templates make sense:
https://github.com/pkp/ojs/blob/ojs-dev-2_4/locale/en_US/emailTemplates.xml#L261
https://github.com/pkp/ojs/blob/ojs-dev-2_4/locale/en_US/emailTemplates.xml#L287
I ask to know if I should take it over to master... :-)
THANKS!!!

**Comment by bozana** [comment]
@asmecher Ah, I see... Please, forget this... :-)

**Pull request merged**
