### PR TITLE
pkp/pkp-lib#589 Bug fix for DOAJ pagination problem

### PR DESCRIPTION
**Pull request by felixgruender**
I fixed a bug in plugins/importexport/doaj/DOAJPlugin.inc.php - the pagination didn't work correctly (by the way - this bug occurs also in the 2.4.6 stable version).

### CODE REVIEW

**Comment by jnugent** [comment]
This looks good, but Travis is not passing the MySQL test.  Please see the build at https://travis-ci.org/pkp/ojs/jobs/70402669 

I think the fail is not related.  @asmecher can you confirm?  It just looks like a weird Selenium problem.

**Comment by asmecher** [comment]
I've restarted the test; it's likely a Selenium hiccough.

**Comment by asmecher** [comment]
@jnugent, do you mind also cherry-picking this into ojs-stable-2_4_6, since it's a small fix?

**Comment by jnugent** [comment]
cherry picked over.

**Comment by asmecher** [comment]
Thanks!

**Pull request merged**
