### PR TITLE
pkp/pkp-lib#1859 Fix site-wide sidebar control.

### PR DESCRIPTION
**Pull request by NateWr**

### CODE REVIEW

**Comment by asmecher** [comment]
(It does look like the tests failed.)

**Comment by NateWr** [comment]
> Looks good -- much cleaner. Are you content with the level of testing you've given this if we're going to include it in a 3.0.1 release within a few days?

@asmecher Yeah I don't know. Given the potential for this to disrupt other things, might be good to hold it back a release cycle.

**Comment by NateWr** [comment]
@asmecher and @bozana, I'm running into this issue with conflicting submodule commits again. Something must be borked in my local repo, but I'm not sure what. I notice that if you look at the submodule commit:

https://github.com/pkp/ojs/pull/1097/commits/a5e4b38417002c3ecc72d8306d7ec76a507254e5

You'll see that @bozana's latest commits to `pkp-lib` are being included as changes in the submodule commit. But the commit hashes in my local `pkp-lib` match those in `pkp/pkp-lib:master`:

```
commit f7a9c3040f922b441750707f7271b3351f0983a9
Author: Nate Wright <natew@notthisway.com>
Date:   Tue Dec 20 13:17:27 2016 +0000

    pkp/pkp-lib#1859 Add getCurrentContextId() GatewayPlugin class as well

commit 48d44f4c8dd21cba789f66fe5b4e57bcb78ed034
Author: Nate Wright <natew@notthisway.com>
Date:   Mon Dec 19 17:34:17 2016 +0000

    pkp/pkp-lib#1859 Fix syntax error introduced in 3d68ac9b7

commit c24e9aef2d65323f092f004faa0a020c28eb2989
Author: Nate Wright <natew@notthisway.com>
Date:   Mon Nov 21 17:52:36 2016 +0000

    pkp/pkp-lib#1859 Refactor lazyload plugins to not check for context depth

commit b29d3f5f6e9ad40a91f51a65aa44b3790a624ee4
Author: Nate Wright <natew@notthisway.com>
Date:   Mon Nov 14 17:55:12 2016 +0000

    pkp/pkp-lib#1859 Fix site-wide sidebar control.

commit e1c6106c463cfa2a5aa2dd3db56a73f06e5a3493
Merge: 6793e90 647e994
Author: bozana <bozana.bokan@posteo.net>
Date:   Tue Dec 20 10:58:17 2016 +0100

    Merge pull request #2116 from bozana/2109-master
    
    pkp/pkp-lib#2109 sub editors access policy

commit 647e994763313ca379cb8596aabc10828356ebef
Author: Bozana Bokan <bozana.bokan@posteo.net>
Date:   Fri Dec 16 20:12:44 2016 +0100

    pkp/pkp-lib#2109 sub editors access policy
```

So I'm not sure what's going on here. I can blow away my fork and start fresh, but I have a few PRs in the queue that would get lost if I did so.

**Comment by asmecher** [comment]
@NateWr, do you have the following in your global gitconfig?

    [branch]
            autosetuprebase = remote

...and the following in your repo's branch configs?

    rebase = true

**Comment by NateWr** [comment]
Looks like no....? Here's my global config:

```
nate@nate-desktop:/var/www/html/ojs/lib/pkp$ git config --global --list
user.email=natew@notthisway.com
user.name=Nate Wright
push.default=simple
```

And my local `pkp-lib` config:

```
nate@nate-desktop:/var/www/html/ojs/lib/pkp$ git config --local --list
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.worktree=../../../../lib/pkp
remote.origin.url=git@github.com:NateWr/pkp-lib.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
submodule.js/lib/pnotify.url=https://github.com/sciactive/pnotify.git
submodule.lib/phpunit-selenium.url=https://github.com/giorgiosironi/phpunit-selenium.git
submodule.lib/swordappv2.url=git://github.com/swordapp/swordappv2-php-library.git
remote.upstream.url=git@github.com:pkp/pkp-lib.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
remote.beghelli.url=git@github.com:beghelli/pkp-lib.git
remote.beghelli.fetch=+refs/heads/*:refs/remotes/beghelli/*
remote.asmecher.url=git@github.com:asmecher/pkp-lib.git
remote.asmecher.fetch=+refs/heads/*:refs/remotes/asmecher/*
remote.bozana.url=git@github.com:bozana/pkp-lib.git
remote.bozana.fetch=+refs/heads/*:refs/remotes/bozana/*
submodule.js/lib/jquery/plugins/spectrum.url=https://github.com/bgrins/spectrum.git
branch.i1859_more_site_settings.remote=origin
branch.i1859_more_site_settings.merge=refs/heads/i1859_more_site_settings
branch.i1787_fix_links_to_tabs.remote=origin
branch.i1787_fix_links_to_tabs.merge=refs/heads/i1787_fix_links_to_tabs
branch.i592_disabled_contexts.remote=origin
branch.i592_disabled_contexts.merge=refs/heads/i592_disabled_contexts
branch.i1765_sidebar_wording.remote=origin
branch.i1765_sidebar_wording.merge=refs/heads/i1765_sidebar_wording
branch.i1762_skip_links.remote=origin
branch.i1762_skip_links.merge=refs/heads/i1762_skip_links
branch.i1565_multilingual_signal.remote=origin
branch.i1565_multilingual_signal.merge=refs/heads/i1565_multilingual_signal
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.i1930_title_prefix.remote=origin
branch.i1930_title_prefix.merge=refs/heads/i1930_title_prefix
branch.ojs-stable-3_0_0.remote=upstream
branch.ojs-stable-3_0_0.merge=refs/heads/ojs-stable-3_0_0
branch.i1740_plupload_button.remote=origin
branch.i1740_plupload_button.merge=refs/heads/i1740_plupload_button
branch.i1847_closed_registrations.remote=origin
branch.i1847_closed_registrations.merge=refs/heads/i1847_closed_registrations
branch.omp-stable-1_2_0.remote=upstream
branch.omp-stable-1_2_0.merge=refs/heads/omp-stable-1_2_0
branch.omp-dev-1_2.remote=upstream
branch.omp-dev-1_2.merge=refs/heads/omp-dev-1_2
branch.theme_option_doc.remote=origin
branch.theme_option_doc.merge=refs/heads/theme_option_doc
branch.i2042_more_theme_api.remote=origin
branch.i2042_more_theme_api.merge=refs/heads/i2042_more_theme_api
branch.i2044_cover_image_urls.remote=origin
branch.i2044_cover_image_urls.merge=refs/heads/i2044_cover_image_urls
branch.i1867_remember_login.remote=origin
branch.i1867_remember_login.merge=refs/heads/i1867_remember_login
branch.i1906_rtl_locale.remote=origin
branch.i1906_rtl_locale.merge=refs/heads/i1906_rtl_locale
branch.i1859_sitewide_sidebar.remote=origin
branch.i1859_sitewide_sidebar.merge=refs/heads/i1859_sitewide_sidebar
branch.i1772_required_attr.remote=origin
branch.i1772_required_attr.merge=refs/heads/i1772_required_attr
```

But I don't believe this should matter. Whenever I rebase, I do it against `upstream/master`:

```
git rebase -i upstream/master
```

And `upstream` is my remote pointing to `git@github.com:pkp/pkp-lib.git`. It's the same workflow that I've been doing for a while now...

**Comment by bozana** [comment]
@NateWr, did you managed to solve the problem? Maybe we can continue the discussion somewhere else and close this PR?

**Comment by NateWr** [comment]
Merged in separate PR: https://github.com/pkp/ojs/pull/1161

Closing.

**Pull request closed without merging**
