### PR TITLE
pkp/pkp-lib#4149 Optionally enable OAI for journals that don't publish with OJS

### PR DESCRIPTION
**Pull request by asmecher**

### CODE REVIEW

**Comment by NateWr** [comment]
One test fell over so I restarted it, should be good by the time you wake up.

This looks like it works ok, but it feels like it introduces complexity to the context model that we could avoid. It took me a long time to figure out how you were actually implementing the feature. I finally realised it was embedded in [this line of SQL](https://github.com/pkp/ojs/pull/2167/files#diff-abb6ff470005a0a704ec234ce02db8a0R243).

I think of these things as someone consuming an API -- in the sense that I want to be able to look at an object's properties and determine the meaning without too much fuss. With this approach, I have the `enableOaiAnyway` property. But I can't rely on this alone. I have to know that if this is `false`, the OAI might still be enabled depending on what the settings of `publishingMode` are. Sometimes these dependencies are unavoidable, but it doesn't seem so here.

I'd much rather have an `enableOai` property that was either `true` or `false` depending on whether OAI was published, and I'd rather the app's code relied on that too, rather than trying to extrapolate it from the `publishingMode` property. (It would also mean someone could choose to publish the frontend and disable OAI, for example if they had a third-party solution).

I can see that you've done things this way because it slots in easily with the Form system, and you don't need to set up context defaults or do any data migration. Maybe I can do the migration and setup for an `enableOai` property as part of the forms PR, so it's in for 3.2? I'd do the following:

- Create `enableOai` prop in context.json
- Set `enableOai` to `true` when a context is created
- When a public publishing mode is selected in the access form, set `enableOai` to `true` in the form
- Migrate existing `enableOaiAnyway` values over to the new system

Probably more than you wanted from the code review! :laughing: You know how itchy I get with these things sometimes. :+1:

**Comment by asmecher** [comment]
Yep, totally legit critique; I'll give it a rework. :+1:

**Comment by asmecher** [comment]
I've moved to a simple `enableOai` setting, but the need for an upgrade script to introduce it for existing users means that we can't add it to `ojs-stable-3_1_1` (upgrade scripts between builds are verboten). That was part of my reasoning for the now-removed `enableOaiAnyway`, but I agree that this introduced some unjustified complexity. So here's my proposal:

- For OJS 3.2, go ahead with your [suggested implementation](https://github.com/pkp/ojs/pull/2167#issuecomment-439410183)
- For OJS 3.1.x, we ask users who need this to apply the [patch](https://github.com/pkp/ojs/pull/2167/commits/a9300d73cdc07e5cd5c3fa838bfd40ed899d8fe0), but we don't commit it to e.g. `ojs-stable-3_1_1`
- Users who have applied the patch to OJS 3.1.x will need to manually review their "Distribution" form and enable the OAI checkbox for journals that should be exposed via OAI.

Sound workable, @NateWr?

**Comment by NateWr** [comment]
Sounds good! I'll include this as part of https://github.com/pkp/pkp-lib/issues/3594 so you can get a code review on it.

**Pull request merged**
