### PR TITLE
pkp/pkp-lib#917 remove references to codehaus.org

### PR DESCRIPTION
**Pull request by bozana**
S. https://github.com/pkp/pkp-lib/issues/917
Could this commit be cherry-picked to ojs-stable-2_4_7, if necessary? Else, I can make a new PR for that branch too...

### CODE REVIEW

**Comment by asmecher** [comment]
@bozana, do you have commit priveleges for the repos? If not, you should. Please go ahead and merge and cherry-pick as needed, this looks fine.

**Comment by bozana** [comment]
@asmecher, hihihi :-) I've just merged the commit to ojs-dev-2_4 :-) Is there a way to cherry-pick it in github (like this merge button), or do I have to cherry-pick and then push?

**Comment by bozana** [comment]
Hmmm... and why are there two entries in the commit list for my merge and only one for your merges?

**Comment by bozana** [comment]
Ah, sorry, there are two for your merges as well... Hihihihi :-)

**Comment by asmecher** [comment]
I usually cherry-pick locally then push. Maybe there is a web-based way, but I haven't seen it.

**Comment by bozana** [comment]
Thanks @asmecher, done :-)

**Pull request merged**
