### PR TITLE
Homepage Image Alt Text Missing

### PR DESCRIPTION
**Pull request by TobiasWantzen**
L. 26 is wrong – »$homepageImage.altText« is the right variable.
And `<div>` was missing.

### CODE REVIEW

**Comment by NateWr** [comment]
HI @TobiasWantzen, what version of OJS are you using? In my copy of the latest `master` branch, which is close to 3.2.0-2, the alt text is working...

**Comment by TobiasWantzen** [comment]
Hej @NateWr, System Information shows me: »Current version: 3.2.0.2 (April 20, 2020 - 07:58 AM)«. I downloaded that shortly before, maybe at 7 AM, from https://github.com/pkp/ojs/releases .

But in the master branch, which I corrected, uses a faulty variable and the surrunding `<div>` ist missing - as you can see above.

**Comment by NateWr** [comment]
You're right! Sorry, I got this confused with the logo and so tested that out instead. Looks like this image was missed for some accessibility changes too. Can you change the logic so that the `alt` attribute does not appear if there is no alt text:

```
{if $homepageImage.altText} alt="{$homepageImage.altText|escape}"{/if}
```

That follows the guidance we got from an accessibility audit.

**Comment by TobiasWantzen** [comment]
> That follows the guidance we got from an accessibility audit.
Okay, I extended the alt attribute with the if-clause.

**Comment by NateWr** [comment]
Thanks @TobiasWantzen! I've merged this to `master` and set up a pull request to port this to the stable branch (so it goes out with OJS 3.2.0-3). https://github.com/pkp/pkp-lib/issues/5778 Once the tests pass I will merge that in.

**Comment by TobiasWantzen** [comment]
Great! Thanks!

**Pull request merged**
