### PR TITLE
New locales (fr_CA) for 2 plugins; modifs on a key

### PR DESCRIPTION
**Pull request by pnault**
Hi,

I made some locale file for plugins theme/defaults and pubIds/doi. I also made some corrections for a key. I have updated my local repository to the master branch (sync) but I'm not sure why, when I pushed my change to my remote repo, all commits from the pull seems to be include, now, in the pull request. The real commits (mine) are:
3288e7c
62b22a2
f3c8c24

I tried `git rebase` but it give me this message:
```
 $ git rebase
First, rewinding head to replay your work on top of it...
Fast-forwarded master to refs/remotes/origin/master.
```
Any idea? I have followed instructions here: https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors on "Keeping your fork in sync with PKP"

Pierre

### CODE REVIEW

**Comment by mtub** [comment]
Hi @pnault, for your locale updates, it's probably best to not merge the master branch changes back into your repository before you get your locale changes merged into PKP's repository. You could work locally on a dedicated local branch:

> git checkout master
> git checkout -b fr-locale-updates
> (translate, translate)
> git add ...
> git commit ...
> git push ... (to your GitHub repo)
> (pull request)

The conflicts you ran into are caused by updated submodules, where the pointers from your OJS repo to a specific point in the history of, e.g., the `pkp-lib` or the `lensGalley` repository differ from the pointers in the master branch.

Here's what you could do to resolve this the easy way:

a) create a new local branch, reset it to the master branch and then cherry-pick your commits
b) ask me to do this ;)

**Comment by mtub** [comment]
Hi @pnault , I will take it from here and merge the three commits 

3288e7c
62b22a2
f3c8c24

**Comment by pnault** [comment]
Hi @mtub 

If I understand you correctly I don't merge the master branch back into my own. How do I update my local branch with the new commit from master? And what do you mean by "create a new local branch, **reset it to the master branch**"

Thanks

**Comment by mtub** [comment]
Hi @pnault , yes, you should update your local branch by merging in the master branch. I was just suggesting that you should not merge the master branch in again just before uploading your locale changes (as long as you only update the fr_CA locale, you will probably not run into any conflicts).

What I meant with the other comment is: If you have commits in your history that you cannot easily revert, you can start from a new local branch that is up to date with the master branch (e.g. by resetting it via `git reset`). You can then apply your good commits by cherry-picking:

git cherry-pick 3288e7c
git cherry-pick 62b22a2
git cherry-pick f3c8c24

and then push your commits and open a pull request.

**Pull request closed without merging**
