### PR TITLE
pkp/pkp-lib#1894: Define specific Dataverse error message to prevent hijacking of NOTIFICATION_TYPE_ERROR

### PR DESCRIPTION
**Pull request by ctgraham**
Resolves pkp/pkp-lib#1894, but the use of the new constant is a TODO,

### CODE REVIEW

**Comment by bozana** [comment]
@ctgraham, shouldn't all the calls of NOTIFICATION_TYPE_ERROR here (when notifications are created) be replaced by the new NOTIFICATION_TYPE_DATAVERSE_ERROR? I see you inserted a TODO comment. Would you be able to check/evaluate it?

**Comment by ctgraham** [comment]
I didn't evaluate these myself because I wasn't confident in knowing for sure when the Dataverse-specific message was appropriate.  I'll happily try a first run-through if you want to check my guesses.

The current message is "An error occured updating this submission's data in Dataverse."

Yes, should be replaced:
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/dataverse/DataversePlugin.inc.php#L604
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/dataverse/DataversePlugin.inc.php#L604
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/dataverse/DataversePlugin.inc.php#L1592
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/dataverse/DataversePlugin.inc.php#L1628

Maybe? Not really Dataverse API specific, but is Dataverse specific?
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/dataverse/DataversePlugin.inc.php#L859
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/dataverse/DataversePlugin.inc.php#L916
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/dataverse/DataversePlugin.inc.php#L975
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/dataverse/DataversePlugin.inc.php#L1033

No, this should probably be a different (more specific) message:
https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/dataverse/DataversePlugin.inc.php#L1560

**Comment by bozana** [comment]
Thanks a lot @ctgraham. But earlier the same message was used for all those cases, right? -- Thus, we could at least do the same, right? I will take a look how it could be improved i.e. better differentiated, but I do not use Dataverse plugin i.e. I am not so familiar with it and I cannot test it...

**Comment by ctgraham** [comment]
Same limitation here.  Since we don't use it and I'm not familiar with it, I'm just guessing based on the code context.

But, yes, to retain the prior function, we could just change all of those references.

**Pull request merged**
