### PR TITLE
fix string translation in Spanish

### PR DESCRIPTION
**Pull request by t4x0n**
fixing manager.setup.enableUserRegistration string in Spanish translation

### CODE REVIEW

**Comment by mtub** [comment]
This looks correct. Will merge, but @marcbria, feel free to have another look.

**Comment by marcbria** [comment]
Unsure about the need of this change... both expressions sounds good to me.
Let me ask our translator.

**Comment by t4x0n** [comment]
I think this is needed because is incorrect in the context

**Comment by marcbria** [comment]
Hi @t4x0n,

First, thanks a lot for your contributions to the spanish translation.

About the issue, why do you say "it's incorrect in this context"?

The literal under discussion is this one:
`<message key="manager.setup.enableUserRegistration">Users can register themselves with the press in one or more of the following roles:</message>`

And appears in the step 4.1 of the Journal configuration. Full text (in context) is:

- [x] **Users can register themselves with the journal in one or more of the following roles:**
  - [x] Readers (will receive notifications and be counted as equivalent to a subscriber)
  - [x] Authors (can submit materials to the journal)Reviewers (available for reviewing submissions) 
  - [x] Reviewers (available for reviewing submissions)

So, in Spanish, the right translation here is:
- "Los usuarios/as pueden registrarse en la revista con uno o varios de los siguientes roles:"

The only template that uses this literal is: /templates/controllers/tab/settings/siteAccessOptions/form/siteAccessOptionsForm.tpl

¿did you find this literal somewhere else?

Cheers,
m.

**Comment by davidalar** [comment]
Hi!... in OJS 3.1.0-1 

I see "Registro de usuarios/as
Los usuarios/as pueden registrarse en la revista con uno o varios de los siguientes roles:"
but but the "following roles" do not appear... see the screenshot here:: https://editoreschile.cl/1.jpg

I should say something similar to this:

English: "Users can register in one or more of the roles enabled in the journal's configuration: Author, Reader, Reviewer." 

Spanish: "Los usuarios/as pueden registrarse en uno o varios de los roles habilitados en la configuración de la revista: autor, lector, revisor."

My English is not good sorry ... for that reason I can not propose a better translation but I think the idea of what I mean is well understood ...

Regards!

**Comment by t4x0n** [comment]
@marcbria you are talking about OJS2? this is an image from OJS2:
image
but in OJS 3 I can't found this step, when I say "in the context" I think in this:
image

**Comment by t4x0n** [comment]
@marcbria is not correct this:
> The literal under discussion is this one:
<message key="manager.setup.enableUserRegistration">Users can register themselves with the press in one or more of the following roles:</message>

this is the string:
<message key="manager.setup.enableUserRegistration">Visitors can register a user account with the journal.</message>

line 167: https://github.com/pkp/ojs/blob/e4a780c7d25e724ac79a8e217f233cafa9c61caf/locale/en_US/manager.xml#L167

**Comment by marcbria** [comment]
You both are right @t4x0n and @davidalar... we checked this in the wrong version. Shame on we. :-1: 

The only change to your proposal is the "gender split" ("desdoblamiento de género") so it need to be "usuario/a". Please, change this detail and mention @mtub to commit the change to the next relase.

Thanks a lot for your help,
m.

**Comment by t4x0n** [comment]
are you sure @marcbria?  because in this case "cuenta de usuario" the word "usuario" is more like an adjective, I understand your proposition but maybe can you corroborate with your translator?

**Comment by marcbria** [comment]
Yes, I'm sure. :-)
I ask him and he told me "usuario" here is a noun and to follow the translation guide, need to be split.

But if for some reason you want to avoid the "gender split" you can write it without the noun.
It could be as something as follows: "Los visitantes pueden crearse una cuenta en la revista".

By context, it's very clear we are talking about a "user account".
All the choices are very close and correct, but I think I like this best... But let's go with the one you like most if it follows the translation guide.

Cheers,
m.

**Comment by t4x0n** [comment]
sorry, pero para corroborar, cuál te gusta más?: 

(1) "Los visitantes pueden crearse una cuenta en la revista"
(2) "Los visitantes pueden registrar una cuenta de usuario/a en la revista."

gracias por la explicación!

**Comment by marcbria** [comment]
Las dos son traducciones válidas, incluso muy buenas...  pero ahora revisando de nuevo el contexto, y solo por un tema estético, optaría por la segunda. Así, en el checkbox se muestran textos de tamaño similar.

Gracias por tu trabajo Carlos.

Un saludo,
Marc.

**Pull request merged**
