### PR TITLE
Italian translation update

### PR DESCRIPTION
**Pull request by marchitelli**
in ojs/locale and in various plugins

### CODE REVIEW

**Comment by mtub** [comment]
Thanks, @marchitelli, this looks good. Discovered English text (that maybe was not left there on purpose) in

'gifts.detailsDescription` and `manager.setup.lockssDescription` - maybe you can have a quick look at these two keys?

**Comment by mtub** [comment]
Thanks, @marchitelli . Could you remove your lib/pkp commit from the pull request? You are updating the submodule so that it points to a commit that has not been published/is not part of pkp-lib. If you want me to fix this after merging, please let me know.

**Comment by marchitelli** [comment]
Hi @mtub, I don't know how remove that commit from my PR (I think that I tried in a wrong way). May you fix after merging, or help me to fix? Thanks!

**Comment by mtub** [comment]
Okay, @marchitelli , I will override the submodule update after merging your pull request. In general, you don't have to commit submodule updates when doing locale updates. The submodule commit tells the application which version (after which commit) of pkp-lib to use (e.g. during the automated Travis CI tests we are running). When you want to commit an update (to OJS, OMP...) that requires particular updates in pkp-lib, you should set your pkp-lib repository to that exact commit, make sure that your commit has been pushed and merged into the PKP repository, and then make a separate commit to your OJS or OMP repository including only the submodule:

git add lib/pkp
git commit

See https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors#Configure_the_PKP-lib_Sub-modules

Thanks for contributing!

**Pull request merged**
