### PR TITLE
pkp/pkp-lib#2686 Add api_key_secret to config template

### PR DESCRIPTION
**Pull request by samplet**
@kaschioudi This is the config template change to go along with pkp/pkp-lib#2686.

### CODE REVIEW

**Comment by kaschioudi** [comment]
Thank you @samplet for you contribution.

Since this change goes along with changes in pkp-lib, it's recommended to also commit a submodule update in order to trigger travis continuous integration. Please see https://pkp.sfu.ca/wiki/index.php?title=Information_for_Developers#PKP_library_submodule_changes

**Comment by samplet** [comment]
@kaschioudi Thanks for pointing out that documentation! Sorry I missed it the first time.

Just FYI: The first CI run I did failed because commit pkp/pkp-lib@9c9245a1 (the current master) breaks the test framework. I changed things around so that that commit wouldn't be included in the submodule update. @asmecher you probably want to do something about that (line 42 https://github.com/pkp/pkp-lib/commit/9c9245a1c4b825f40de4354c1051e04d8a4288ae#diff-18654a71dce0916d078318ca2a5c52f6R42 is missing a `#` at the beginning). :wink:

**Comment by asmecher** [comment]
Thanks, @samplet -- @NateWr already caught and fixed it, so a rebase should take care of it.

**Comment by kaschioudi** [comment]
thank you very much @samplet . 

@asmecher this feature is ready for merge. Do you want me to merge it or you will take care of it?

**Comment by asmecher** [comment]
Hi @kaschioudi -- please go ahead if it's ready!

**Comment by NateWr** [comment]
@kaschioudi Should this get in with 3.1?

**Comment by kaschioudi** [comment]
@NateWr . This feature has been merged few days ago (see https://github.com/pkp/ojs/pull/1573) 
This PR can be closed. Thanks.

**Pull request closed without merging**
