### PR TITLE
Remove the UI elements for the pln_url config variable.

### PR DESCRIPTION
**Pull request by ubermichael**
It isn't necessary and it causes quite a bit of confusion for the journal managers. Also removes the pln_network* locale keys and settings.xml config. 

Fixes pkp/pkp-lib#1043

### CODE REVIEW

**Comment by asmecher** [comment]
Is there no use case for different journals in the same installation to have different PLN URLs? (I don't know of one, but this does remove support for it.)

**Comment by ubermichael** [comment]
We couldn't think of one. If it becomes important to someone in the future, we could make something like this work:

    pln_url[abc] = http://...
    pln_url[def] = http://...

But at this point it doesn't seem to be worth it.

**Comment by asmecher** [comment]
Agreed. Could you add a `docs/dev/release-notes/README-2.4.8 describing the new configuration options? Have a look at e.g. `docs/release-notes/README-2.3.0` for an example.

**Comment by ubermichael** [comment]
Done and done.

**Pull request merged**
