### PR TITLE
pkp/pkp-lib#4097: fix grouping when ordering issues by custom sequence

### PR DESCRIPTION
**Pull request by crism**
Addresses the proximate issue for pkp/pkp-lib#4097. Probably we should look at test coverage for PostgreSQL, though…

### CODE REVIEW

**Comment by crism** [comment]
This should also fix https://forum.pkp.sfu.ca/t/ojs-3-1-1-2-db-error-in-archive-view/47151/3

**Comment by asmecher** [comment]
Thanks, @crism, the fix looks good. Have you looked at the CLA yet? We're just about to publish a plainish-text blog post about it, FWIW.

**Comment by crism** [comment]
@asmecher, did sign it… but wasn’t accepting cookies for cla-assistant.io, so it couldn’t tell. Should be done now.

**Comment by asmecher** [comment]
Great, thanks, @crism! @NateWr, mind taking a quick look over it? It's a one-liner. (Ignore the test failures -- that's my fault and has already been fixed in the `master` branch.)

**Comment by NateWr** [comment]
I don't see any issues with it. :+1:

**Comment by asmecher** [comment]
Cherry-picked in manually -- thanks, @crism!

**Pull request closed without merging**
