### PR TITLE
Add citationStyleLanguage instructions to README

### PR DESCRIPTION
**Pull request by nuest**
Just a small step I had to complete creating a dev env on a machine that has never seen OJS before.

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @nuest! @NateWr, this is already part of the build script, right?

**Comment by asmecher** [comment]
(Oh -- it should probably also go here: https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors#Install_Composer_dependencies)

**Comment by nuest** [comment]
Is `ojs/tools/buildpkg.sh` the "build script"?

Cool, there's a Travis config file. I wish I've discovered that before digging into the error messages ;-)

**Comment by NateWr** [comment]
@asmecher Yes, this is in `tools/buildpkg.sh`.

**Comment by asmecher** [comment]
Thanks, @NateWr -- may I leave this PR with you? Seel also the wiki link above.

**Comment by NateWr** [comment]
@asmecher I've merged the PR. But I can't seem to create an account on the wiki. Is it invite only?

**Comment by NateWr** [comment]
ps - thanks @nuest!

**Comment by asmecher** [comment]
@NateWr, yes, I think so -- @jmacgreg should be able to help.

**Pull request merged**
