### PR TITLE
pkp/pkp-lib#1762 Add skip-to links for keyboard and screen-reader users

### PR DESCRIPTION
**Pull request by NateWr**

### CODE REVIEW

**Comment by bozana** [comment]
@NateWr, I in the submodule update commit I see two classes, that are not part of the pkp-lib PR: `classes/admin/form/PKPSiteSettingsForm.inc.php` and `controllers/tab/settings/siteSetup/form/SiteSetupForm.inc.php` . Are those changes already merged i.e. could you then at the end either add or remove them before doing the submodule update commit?

**Comment by NateWr** [comment]
@bozana I'm sorry I'm not really sure what you mean in [this comment](https://github.com/pkp/ojs/pull/1079#issuecomment-260941401). I think both of those classes are in `pkp-lib`?

**Comment by bozana** [comment]
@NateWr, hmmm... When I look at the pkp-lib PR commit https://github.com/pkp/pkp-lib/pull/1936/commits/4cf3c5072e6bac496cf19fe826e5f89f153f9bc9, I do not see any changes on those classes/files, but in the application submodule changes commit e.g. https://github.com/pkp/ojs/pull/1079/commits/f8e346a2de27b5db46bcef42f01978d7eebb050d I saw them i.e. now I see another class plugins/importexport/users/filter/UserXmlPKPUserFilter.inc.php :-O I don't know what that means?

**Comment by NateWr** [comment]
Hmm, yeah I'm not sure what that means. I noticed that GitHub recently changed the way that it displays these submodule commits.

Kind of annoying since I used to use the commit hashes to ensure my PRs were based against the right submodule commit.

But I'm not sure why those changes show up. Maybe it has to do with which commits it has been rebased on top of? I notice that that `UserXmlPKPUserFilter.inc.php` is your fix to that import/export issue. I don't know...

**Pull request merged**
