### PR TITLE
Limit the number of revision uploaded messages

### PR DESCRIPTION
**Pull request by ajnyga**
At the moment the system sends a notification for each uploaded revision file. If the author happens to upload several files and/or uploads a sligthly modified version of a file, the editors may end up receiving tens of emails.

This pr first checks if there is a recent (within the last 15 minutes) notification message that has been sent. If there is, new emails are blocked.

Needs https://github.com/pkp/pkp-lib/pull/4071, that was merged to master recently.

### CODE REVIEW

**Comment by asmecher** [comment]
@ajnyga, is there a PR open against `pkp-lib`? All I see referenced here is the submodule update in https://github.com/pkp/ojs/pull/2152.

**Comment by ajnyga** [comment]
ah, ok, forgot that you need that too. Here: https://github.com/pkp/pkp-lib/pull/4202

For some reason one of the tests failed, but can not see how that is connected to this pr?

**Comment by asmecher** [comment]
That test looks like a hiccough rather than an error -- I've restarted it and I expect it'll pass this time.

Just for consideration, what about this: rather than an arbitrary 15 minute threshold, how about checking the sessions table to see whether the user has been active since the last message was sent?

**Comment by ajnyga** [comment]
Sure, I think @NateWr suggested something similar as well. I will look at it tomorrow.

**Comment by ajnyga** [comment]
Maybe something like this @asmecher

**Comment by ajnyga** [comment]
I just keep on getting failed tests with this. First it was something todo with npm builds and now it is something to do with the submission form and the cancel button. Both of course things that the changes here do not touch at all.

**Comment by NateWr** [comment]
It looks like the file upload wizard is not opening:

https://travis-ci.org/pkp/ojs/jobs/452274068#L1380

Looking at what was running when this happens, it looks like it's the move from step 1 to step 2 of the submission process.

https://github.com/pkp/pkp-lib/blob/master/tests/PKPContentBaseTestCase.inc.php#L102

The file upload wizard should pop up but doesn't appear to be doing so in the tests. That could mean the ajax request that's fired off to open it up is returning something wrong.

The first thing I'd recommend is to try out a submission yourself and see if the file upload wizard pops up automatically. If not, you can start looking for the problem there.

**Comment by ajnyga** [comment]
So I fixed the issue but now the tests failed in an earlier stage while doing npm builds. I am now rerunning.

**Comment by ajnyga** [comment]
And the same thing again. No idea how to fix that.

**Comment by ajnyga** [comment]
I give up, this is taking way too much time. The changed file is here: https://github.com/pkp/pkp-lib/pull/4224/files

**Comment by NateWr** [comment]
@ajnyga do you have an issue number for this?

**Pull request closed without merging**
