### PR TITLE
Added some german translations

### PR DESCRIPTION
**Pull request by henkela**

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @henkela -- FYI, the Travis tests are failing because Travis doesn't know how to find your branch of the lib/pkp submodule. There's a little documentation on how we've worked around this:

https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors#PKP_library_submodule_changes

**Comment by henkela** [comment]
Thanks, @asmecher. I tried to git add lib/pkp but for some reason it doesn't work. Couldn't figure the problem yet.

**Comment by asmecher** [comment]
Hi @henkela -- the trick is to make the lib/pkp submodule commit the last commit in the list, and formulate the commit message as described in the wiki article. The Travis testing setup script will look for that special commit and find your branch using it.

**Comment by henkela** [comment]
Hi @asmecher, thanks for the hints. I got the point. I'm rather struggling with my local git that denys to stage lib/pkp...

**Comment by asmecher** [comment]
@henkela, I tend to make a lot of use of e.g. `git rebase -i official/master` (with `official` as the PKP remote). That's an interactive rebase, where I can move the `lib/pkp` submodule down to the bottom, squash subsequent submodule commits into it, and maintain the commit message as the Travis script expects it. It's a little painful but unfortunately I'm not sure of a better way and `git rebase -i` is really useful to help.

**Comment by henkela** [comment]
@asmecher, I see. Now I'm facing to problems with that. The first one is that git rebase tells me warning: Failed to merge submodule lib/pkp (merge following commits not found)
Could not apply eb7931a06d2f09ebd26008ba2c6c5d925c6d6d0e... pkp/lib#1505 german language adaption in lib/pkp

Additionally, running git add lib/pkp doesn't stage the files nor can I  set up a commit. 

Any hints welcome.

**Comment by henkela** [comment]
I'm sorry but I don't get travis to pass and just make a mess with my trials...

**Comment by asmecher** [comment]
@mtub, could you review the changes? I can cherry-pick this in once it looks good. Since it's just translation changes, I'm not worried about the tests failing.

@henkela, could you open a pull request for the `lib/pkp` part of the update? Don't worry overmuch about getting the commits right. (Or if you already did open a PR, drop a link here.)

**Comment by henkela** [comment]
@asmecher, I went the hard way, deleted my fork, made a fresh fork of ojs and made a clean commit of my changes (pull request #857). There again git add lib/pkp didn't work - git didn't throw an error or warning but just didn't stage the files changed in the submodule. Therefor, I made a seperate clone of pkp-lib and commited directly. 
And as I write you already added that pull request :-)

**Comment by asmecher** [comment]
Superseded by https://github.com/pkp/ojs/pull/857.

**Comment by asmecher** [comment]
@henkela, welcome to the joys of submodules, unfortunately. They're very finicky but they do work -- once you've started thinking like one. However, translation updates aren't likely to break the tests, so no need to worry about it.

**Pull request closed without merging**
