### PR TITLE
sl_SI 3.1.2  update

### PR DESCRIPTION
**Pull request by primoz-svetek**
@mtub  This is the sl_SI update for the OJS 3.1.2 Pleate let me know if PR is done OK.

### CODE REVIEW

**Comment by primoz-svetek** [comment]
I don't know what is wrong, but I signed CLA several times nad still say not signed :(

**Comment by asmecher** [comment]
@primoz-svetek, I think there are some accidental changes included in the commit -- e.g. a bunch of submodule updates. I suspect that's connected.

**Comment by primoz-svetek** [comment]
@asmecher  So sorry. I am still learning GitHub. Is there anything I can do about this? I mean, I will create PR for each submodule separately, I know I have to do that. But to get this PR merged...

**Comment by asmecher** [comment]
@primoz-svetek, no problem, github has a big learning curve and submodules are on the steeper slopes of that :)

I would suggest leaving the submodule updates out -- we can take care of them over here (and I typically do that before every release, to ensure that everything is up to date)!

I suspect that if you remove the submodule updates from the PR, and just include your changes to the locale files, you'll see the list of contributors drop to just you (and the CLA issue will go away too).

**Comment by primoz-svetek** [comment]
@asmecher  If you let me know what shoudl I do now, would be very happy. The poing is I have changed files only in locals/sl_SI. But git somehow found also others. The probem might be as I used executed  'git add -R .'

**Comment by asmecher** [comment]
I'm not familiar with `-R` to `git add`, but that might be the issue if it's e.g. like `git add -A`. Removing the submodule changes can be a bit of a pain; the easiest way might be to close this PR down and create a new one from a new branch, just calling `git add` on the files you want to include.

**Pull request closed without merging**
