### PR TITLE
    fixed small typo

### PR DESCRIPTION
**Pull request by Cloud8**
geändert:       dbscripts/xml/upgrade/3.0.0_update.xml

### CODE REVIEW

**Comment by bozana** [comment]
@Cloud8, I think that line should be like the line before i.e. with `article_galleys_migration agm` -- would you like to change it once again?

**Comment by Cloud8** [comment]
Yes, I will re-run the whole update process and change this PR as you suggested

**Comment by bozana** [comment]
closing and reopening because of tests....

**Comment by bozana** [comment]
Grrr... I have no idea why there is the time out in the tests...

**Comment by bozana** [comment]
Thanks a lot @Cloud8 !!! :-)

**Pull request merged**
