### PR TITLE
Add cookie consent option for GDPR compliance

### PR DESCRIPTION
**Pull request by ajnyga**
@NateWr @asmecher 

https://github.com/pkp/pkp-lib/issues/3624

A new try on https://github.com/pkp/ojs/pull/2010 (for some reason even when I merged the changes from upstream github kept telling me there are conflicts...)

### CODE REVIEW

**Comment by ajnyga** [comment]
@NateWr the tests failed (again). This time I can not find a php related error in the logs, or I just do not know how to search for one. Any thought?

**Comment by ajnyga** [comment]
hmm, I have a feeling that the change in the login form is something that is not taken into account in the test script?

**Comment by NateWr** [comment]
Yeah, it takes a while to get used to what to look for in the tests. It looks like one of the tests failed, as you suspected, during login:

```
There was 1 error:

1) CreateJournalTest::testCreateJournalLogin
Current URL: http://localhost/
Screenshot: http://localhost/lib/pkp/tests/results/c25011905cc46ed32b921973ebab3b37.png

WaitFor timeout. 
Last exception message: 
Failed command: waitForElementPresent('link=Login')
Failed asserting that false is true.
```

So the next step is to look up that test (class `CreateJournalTest`, method `testCreateJournalLogin`). That leads us to https://github.com/pkp/pkp-lib/blob/master/tests/WebTestCase.inc.php#L117-L135 with the username `admin` and password `admin`.

This part:

```
Failed command: waitForElementPresent('link=Login')
```

Tells us that it is looking for a Login link on [this line](https://github.com/pkp/pkp-lib/blob/master/tests/WebTestCase.inc.php#L127) but not finding it.

Now the hard part. Any idea why the Login link might not be appearing? It looks like it is set to not appear when the `Validation::isLoggedIn()` is `true`. Is there any way that this change might be effecting the value of that method?

**Comment by ajnyga** [comment]
Thanks @NateWr I see now, that one of the changes I did to validation.inc.php was not included in pull request for some reason. It was probably causing that, because it involved the isLoggedIn method.

So I gave it another go, let's see what happens...

**Comment by ajnyga** [comment]
@NateWr seems to get stucked to the same error.

The changes I made to the isLoggedIn method are here: https://github.com/pkp/pkp-lib/compare/e0e3bd09f968794a171484d2f9035d52482a6390...b54819e9a4ad915d73aff668ece62db012ce4fe9#diff-22f011e60fab54877fdfd4efb4dcbfa6R386

I can not see how that would cause the login link from being hidden. Especially while you need to turn on these new features from the config.inc.php (see the changes for the config template) and I do not think the test scripts would do that at the moment?

**Comment by NateWr** [comment]
Can you share the link for the associated PR for pkp-lib? I went looking but couldn't find it.

**Comment by NateWr** [comment]
You'll need to issue a PR for `pkp-lib` too. Can you do that? I don't think that would be causing the tetst failures, but I'll check it out and see if I can reproduce the problems at all.

**Comment by ajnyga** [comment]
https://github.com/pkp/pkp-lib/pull/3886

**Comment by NateWr** [comment]
Thanks! So I loaded up these branches and got this db error:

```
<h1>DB Error: Data too long for column 'ip_address' at row 1</h1>ojs2: DB Error: Data too long for column 'ip_address' at row 1
```

I then went back to look at the Travis tests here: https://api.travis-ci.org/v3/job/400988328/log.txt  At the very bottom of the apache error log I see a similar error:

```
[06-Jul-2018 17:46:26 UTC] ojs2: DB Error: ERROR:  value too long for type character varying(39)
[06-Jul-2018 17:46:26 UTC] ojs2: DB Error: ERROR:  value too long for type character varying(39)
[06-Jul-2018 17:46:26 UTC] ojs2: DB Error: ERROR:  value too long for type character varying(39)
[06-Jul-2018 17:46:26 UTC] ojs2: DB Error: ERROR:  value too long for type character varying(39)
[06-Jul-2018 17:46:26 UTC] ojs2: DB Error: ERROR:  value too long for type character varying(39)
[06-Jul-2018 17:46:27 UTC] ojs2: DB Error: ERROR:  value too long for type character varying(39)
[06-Jul-2018 17:46:27 UTC] ojs2: DB Error: ERROR:  value too long for type character varying(39)
[06-Jul-2018 17:46:27 UTC] ojs2: DB Error: ERROR:  value too long for type character varying(39)
[06-Jul-2018 17:47:14 UTC] ojs2: DB Error: ERROR:  value too long for type character varying(39)
[06-Jul-2018 17:47:14 UTC] ojs2: DB Error: ERROR:  value too long for type character varying(39)
```

Does that provide any hints about what's going on? I'm not great with DB stuff so we may have to call Alec or Bozana in.

**Comment by NateWr** [comment]
Yeah give it a shot. Even if that's not the test failure, at least I'll be able to run it myself to look into it.

**Comment by ajnyga** [comment]
Closed, see https://github.com/pkp/ojs/pull/2106

**Pull request closed without merging**
