### PR TITLE
[OJS] #2910 navigation menus authorisation

### PR DESCRIPTION
**Pull request by defstat**

### CODE REVIEW

**Comment by asmecher** [comment]
@defstat, this didn't get merged, though it looks like it's cosmetic. Is it still needed?

**Comment by asmecher** [comment]
@defstat -- ping! I suspect this is outdated, but I'm not sure.

**Comment by defstat** [comment]
@asmecher the 258c18a "Review Changes" commit should have been merged.

**Comment by asmecher** [comment]
OK, I'll assume this got superseded by another PR. Closing.

**Pull request closed without merging**
