### PR TITLE
fix reassign DOIs

### PR DESCRIPTION
**Pull request by ajnyga**
https://github.com/pkp/pkp-lib/issues/5473

### CODE REVIEW

**Comment by ajnyga** [comment]
@asmecher can you check the tests and maybe restart?

**Comment by asmecher** [comment]
Sorry for the wait -- restarted!

**Comment by ajnyga** [comment]
thanks, tests worked!

**Comment by ajnyga** [comment]
Also @asmecher, I went with option B here: https://github.com/pkp/pkp-lib/issues/5473#issuecomment-582939890

Even if in OJS the DOI does not change with versions, this is still safe, because only the DOI from the latest version is registered and the Crossref plugin there, I think, always just registers one DOI per submission

In OPS the Crossref plugin will register all DOIs within a submission, because versions are supported.

**Comment by asmecher** [comment]
Excellent, thanks, @ajnyga!

**Pull request merged**
