### PR TITLE
Run webpack during build script

### PR DESCRIPTION
**Pull request by NateWr**
@asmecher is this what you were looking for regarding building JS for release packages?

### CODE REVIEW

**Comment by asmecher** [comment]
The built JS should also be updated in the git repo, correct? In that case, add a note to `docs/dev/RELEASE` documenting that.

**Comment by NateWr** [comment]
I've actually put `js/build.js` into the `.gitignore` file. Would you like to see it introduced into version control?

(There's also a `build.js.map` file, which is only used for debugging in devtools. I presume we wouldn't version control that.)

**Comment by asmecher** [comment]
I suggest we treat this similarly to the minified JS:

For the master branch, we can assume users will be working with the Node dev environment, and do not commit the JS build.

For stable branches, some users (including ourselves) will be hosting from git, but won't expect a dev environment. The stable branches should include the built JS.

This needs noting in `docs/dev/RELEASE` so that the extra build/commit step isn't forgotten.

**Comment by NateWr** [comment]
Oh that makes sense. What exactly do I need to note? Should I include a new step that says "remove `js/build.js` from the `.gitignore` file"? Would that do the trick?

**Comment by asmecher** [comment]
@NateWr, I'd suggest leaving it out of `.gitignore` (like we do for minified JS) and putting a note in `docs/dev/RELEASE alongside:

    WARNING: If the release is to have minified JS, set the default in
    config.TEMPLATE.inc.php and compile and commit the latest JS before tagging!

**Comment by NateWr** [comment]
Oh, so are you saying we should commit the `js/build.js` file to `master` as well?

I guess it's a little bit different because `js/build.js` is always loaded, regardless of whether `enable_minify` is on. The app loads that file. We just build it differently depending on whether we're building for development or production (the dev build is nearly 1mb!).

With node build processes, you usually use a `NODE_ENV` config setting to specify `development` or `production` environments, and then configure your build to that environment. You always build to the same target, but you compile differently depending on the environment.

By running `npm run build` in the `buildpkg.sh`, we're forcing a production environment and building the package. But I don't think we'd want to version control that build file in the `master` branch. Otherwise, various developers might have commit files built for dev or production.

If we want people to be able to run OJS off of a stable branch's files without any compilation step, it might make more sense to modify the `.gitignore` file before running `buildpkg.sh` and commit it all. Down the line we won't just have `js/build.js` but will likely be compiling CSS as well (from our single-file vue components). And we'll probably want to exclude the UI library submodule from these branches too when we integrate that.

**Comment by asmecher** [comment]
For the moment, I'd avoid adding `js/build.js` to the `master` branch. I think we're agreed on that.

I suppose we could consider treating the NPM build like we do Composer dependencies -- included in the `.tar.gz` builds, but excluded from git commits. My worry is that we'd make it really hard for people to run OJS in production from git, because the NPM toolset won't be routinely available.

**Comment by asmecher** [comment]
Yes, thanks!

**Comment by NateWr** [comment]
Ok, all done. Merge when ready. (There's also the [OMP pull request](https://github.com/pkp/omp/pull/430)).

**Pull request merged**
