### PR TITLE
ROR Id support for default template

### PR DESCRIPTION
**Pull request by withanage**
Issue:
https://github.com/pkp/pkp-lib/issues/5912

### CODE REVIEW

**Comment by NateWr** [comment]
Let's only link the icon, not the full name of the institution, to the `rorId`. Once that's changed, I'm happy to merge this but I would prefer to merge this only when the plugin is available in the galley. Are you close to a release?

**Comment by withanage** [comment]
@NateWr 

Thanks! Have changed it. 

 I have finished the plugin  already for the first release and  asked some people to test.  Have to write the README. This Thursday, I will finish  that  and will create a plugin-gallery PR.

**Comment by NateWr** [comment]
Ok let me know on Thursday. I'd like to get it into the 3.3 RC if we can.

**Comment by NateWr** [comment]
Ok, i've merged this to stable-3_2_1 and forward-ported it to the `master` branch for 3.3.

**Pull request merged**
