### PR TITLE
pkp/pkp-lib#2547: translate event log message in event details page

### PR DESCRIPTION
**Pull request by ctgraham**
Resolves pkp/pkp-lib#2547; should be cherry-picked to stable 2.4.8.

### CODE REVIEW

**Comment by bozana** [comment]
closed and reopened because of the tests...

**Comment by bozana** [comment]
Hmmm... I will try to run the tests locally -- just to be sure... @asmecher, those tests should pass, right?

**Comment by ctgraham** [comment]
This looks a lot like the same Travis problem which necessitated this change in master:
https://github.com/pkp/ojs/commit/2000a9498a975c3d1542b29e377f6524662187b7

**Comment by asmecher** [comment]
Agreed, @ctgraham -- I didn't back-port that to `ojs-dev-2_4`. Please do so, @bozana, thanks!

**Comment by bozana** [comment]
My local tests passed, so I will merge...

**Comment by bozana** [comment]
Should this be cherry-picked to ojs-stable-2_4_8? I would say yes...

**Pull request merged**
