### PR TITLE
pkp/pkp-lib#1956 XML export validation message encoding

### PR DESCRIPTION
**Pull request by bozana**
s. https://github.com/pkp/pkp-lib/issues/1956

### CODE REVIEW

**Comment by bozana** [comment]
What do we do with those PHP 7 tests, that failed?

**Comment by bozana** [comment]
Oh, I see, I have to rebase -- to disable those PHP 7 tests -- I'll try...

**Comment by bozana** [comment]
I hope you don't mind my monologues here at GitHub :-DDD

**Comment by WaDelma** [comment]
No I don't mind :smile:

**Pull request merged**
