### PR TITLE
pkp/pkp-lib#4076 Catch tests failures of plugins ##ptrckb/plugins-tests##

### PR DESCRIPTION
**Pull request by ptrckb**
In `runAllTests.sh`, the `find` command searching for tests of application plugins was hiding the status of the individual tests.

This PR for `ojs-stable-3_1_1` includes two commits cherry-picked from `master` to fix the now fatal failures in plugins tests.

### CODE REVIEW

**Comment by asmecher** [comment]
@ptrckb, this looks like it just contains a submodule update. Do you have a PR open against the pkp-lib repository?

**Comment by ptrckb** [comment]
@asmecher done now.

The tests for `lensGalley` now exposes a SQL error (with postgresql and masked with mysql): visiting the 'Archives' page fails with :
```
DB Error: ERROR: column "o.seq" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: ...published" = $2 group by "i"."issue_id" order by "o"."seq" ... ^
```
The problem [existed already but was ignored](https://travis-ci.org/pkp/ojs/jobs/430878829#L2604) by the script.

This is has been reported in [this forum post](https://forum.pkp.sfu.ca/t/ojs-3-1-1-2-db-error-in-archive-view/47151) and introduced by f89b23c45ac25924da9a41afac8c445e4d6b2968

Modifying the [`groupBy` clause of `IssueListQueryBuilder::get()`](https://github.com/pkp/ojs/blob/0ab7c264735e03c6a09dacfc7f027caf2f6a3464/classes/services/queryBuilders/IssueListQueryBuilder.inc.php#L161) to instead read:
```php
->groupBy('i.issue_id', $this->orderColumn);
```
make all tests pass (but is most probably not the correct way to fix the problem).

**Comment by asmecher** [comment]
Thanks, @ptrckb. @NateWr, could you look at https://github.com/pkp/ojs/pull/2120#issuecomment-423159096? That might need filing/fixing as a separate issue.

**Comment by NateWr** [comment]
This was filed shortly after your comment by @crism: https://github.com/pkp/pkp-lib/issues/4097

**Pull request closed without merging**
