### PR TITLE
3.1.2 stable fr_Fr translations added

### PR DESCRIPTION
**Pull request by mpbraendle**

### CODE REVIEW

**Comment by asmecher** [comment]
Hi @mpbraendle -- looking at the included commit list, I suspect this was submitted against the wrong branch. Can you double-check?

**Comment by mpbraendle** [comment]
Shall I do against 3.1.2 stable?

**Comment by mpbraendle** [comment]
I have taken the 3.1.2 stable branch and forked it because I derived the change from our test system that runs on 3.1.2

**Comment by asmecher** [comment]
Try closing this pull request (and your other one), and opening a new one. When you create the pull request you'll have the chance to choose a branch to submit it to; rather than `master`, choose `stable-3_1_2`. You should see a commit list that only contains your commits (rather than the commit list above, which has a lot of other stuff).

**Comment by asmecher** [comment]
Same as https://github.com/pkp/ojs/pull/2338#issuecomment-475308791:

> Try closing this pull request (and your other one), and opening a new one. When you create the pull request you'll have the chance to choose a branch to submit it to; rather than master, choose stable-3_1_2. You should see a commit list that only contains your commits (rather than the commit list above, which has a lot of other stuff).

**Comment by mpbraendle** [comment]
Thanks. Got it!

**Pull request closed without merging**
