### PR TITLE
Add Journal Favicon to Website Settings > Appearance

### PR DESCRIPTION
**Pull request by selwyntcy**
Refer to pkp/pkp-lib#1168

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @selwyntcy! I merged this myself to avoid submodule merge conflicts.

**Comment by selwyntcy** [comment]
Thanks, @asmecher!

I'm new to git. Seems that I should skip the submodule commit in pull requests like this, right?

**Comment by asmecher** [comment]
Git with submodules is a pretty peculiar beast; we've written some scripts to permit the CI testing to run with submodule changes properly checked out, but you'll need to format your last commit (the submodule update) in a particular way. See https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors#PKP_library_submodule_changes for info.

**Comment by selwyntcy** [comment]
I see. Let me try next time :)

**Pull request closed without merging**
