### PR TITLE
pkp/pkp-lib#6596 Handle missing Subscription Manager email address be…

### PR DESCRIPTION
**Pull request by Vitaliy-1**
…fore sending the email

### CODE REVIEW

**Comment by NateWr** [comment]
@Vitaliy-1 the code here looks ok. However, it doesn't address the comment in the issue description, regarding the check for `notifyEmail`. Was this a wrong assumption? Should the `if($this->getData('notifyEmail')` conditional block still be in the two subscription forms?

Also, the issue is assigned the `stable-3_3_0` milestone, so you'll need a PR for that too.

**Comment by Vitaliy-1** [comment]
@NateWr, the issue with email sending was fixed a while ago during email refactoring. The option to send an email was re-added into both forms, it sends notification regarding subscription details and should be in both subscription forms. This is a fix to a small bug I found during testing.

**Comment by NateWr** [comment]
Hmm, I guess I've misunderstood. Can you look at https://github.com/pkp/pkp-lib/issues/6596 and do what's necessary to address the bug in 3.3 if it's been fixed in 3.4? Or if this is completely unrelated to https://github.com/pkp/pkp-lib/issues/6596 maybe change the commit message to point to a more appropriate issue?

**Comment by Vitaliy-1** [comment]
Looking at this closer, the SubmissionForm has a custom validator that doesn't work. It should handle the problem I'm trying to solve in this PR. Need to update the PR and backport implementation and the fix to 3.3

**Pull request merged**
