### PR TITLE
Add generic plugin pdfJsViewer at 2.4.x

### PR DESCRIPTION
**Pull request by ctgraham**
Resolves pkp/pkp-lib#1848, though we may want this at [dev head instead](https://github.com/pkp/pdfJsViewer/tree/ojs-dev-2_4)?

### CODE REVIEW

**Comment by asmecher** [comment]
I think that commit is on the `master` branch, no? OTOH I think the `ojs-dev-2_4` is best for OJS 2.4.x.

**Comment by ctgraham** [comment]
No, the commit is the current head of https://github.com/pkp/pdfJsViewer/tree/ojs-2_4_x .  It's one currently commit behind https://github.com/pkp/pdfJsViewer/tree/ojs-dev-2_4 , which updates the copyright dates.

**Comment by asmecher** [comment]
Thanks, that makes sense -- merged. It looks like one of the tests has broken, but that's independent of this change.

**Comment by asmecher** [comment]
Also merged over to `ojs-dev-2_4`.

**Comment by ctgraham** [comment]
The merge to ojs-dev-2_4 will have moved that branch back one commit in the submodule, losing the copyright updates.

**Comment by asmecher** [comment]
Thanks for the heads-up -- I thought I used the same commit, but perhaps I made a mistake. Leaving last year's copyright dates won't cause any problems.

**Pull request merged**
