### PR TITLE
Consider  in article_summary.tpl and search.tpl, change searchHandler…

### PR DESCRIPTION
**Pull request by ajnyga**
… journalmustpublispolicy conditional

See: https://github.com/pkp/pkp-lib/issues/2010

### CODE REVIEW

**Comment by get04** [comment]
Dear Ajnyga, 
The site wide search was not working and after doing the changes you suggested it searches , but the problem is the path with the search results. I made the changes from your commit, but still no success. Could you please help? btw i am using ojs 3.0.2
regards

**Comment by ajnyga** [comment]
I wonder if it is a cache issue with the old article_summary.tpl?

**Comment by get04** [comment]
http://10.6.71.154/index.php/index/user/authorizationDenied?message=user.authorization.contextRequired
I cleared the cache and checked , but no success
Thanks

**Comment by ajnyga** [comment]
I mean the link in the list of search results, the link that should lead to the article.

**Comment by get04** [comment]
10.9.6.23/index.php/index/article/view/9

**Comment by ajnyga** [comment]
So does line 24 look like this:
`<a {if $journal}href="{url journal=$journal->getPath() page="article" op="view" path=$articlePath}"{else}href="{url page="article" op="view" path=$articlePath}"{/if} class="file">`

**Comment by get04** [comment]
yes,it looks the same

**Comment by ajnyga** [comment]
and you have also added the changes to templates/frontend/pages/search.tpl

**Comment by get04** [comment]
Ok, Thanks. Then i wait to hear any update after your test.

regards

**Comment by ajnyga** [comment]
do you use some custom theme, like bootstrap https://github.com/NateWr/bootstrap3/

**Comment by get04** [comment]
yes, i used that

**Comment by ajnyga** [comment]
Hi,

The problem is either
1) an issue I fixed with https://github.com/pkp/ojs/pull/1371/files
2) if you use the bootstrap theme, the template files there will be used instead and at the moment they do not include this modification. @NateWr

**Pull request merged**
