### PR TITLE
Add submenu to payments settings menu

### PR DESCRIPTION
**Pull request by ajnyga**
ping @asmecher 
discussed in https://forum.pkp.sfu.ca/t/some-problems-with-subscriptions-after-upgrade-to-3-1-0-1/37347/4

### CODE REVIEW

**Comment by ajnyga** [comment]
A general thing I noticed with these submenus. At least with Firefox, if you open for example the Future numbers tab and the try to go to the back issues page by clicking the link from the submenu, the link does not work. You can enter back issues by clicking the link in the tab.

**Comment by asmecher** [comment]
@NateWr, I recall you raised this before as a known quirk? https://github.com/pkp/ojs/pull/1803#issuecomment-359812012

**Comment by NateWr** [comment]
Yes, I'm aware of it. I'm not really sure what to do about it, but our tabs-as-URLs doesn't seem very bulletproof. I've mentally off-loaded it as something to solve when we refactor tabs to Vue.js.

**Comment by ajnyga** [comment]
ping @asmecher maybe this could make it to 3.1.1? It is a fairly simple addition.

**Comment by asmecher** [comment]
Agreed! Thanks, @ajnyga.

**Comment by ajnyga** [comment]
Great, do you think if a do pr, would this get included in time as well: https://github.com/pkp/pkp-lib/issues/3330
In brief: journals may want to use an embargo also without enabling payments and that is not possible at the moment. So the embargo length setting should be in `Settings => Distribution => Access`

**Comment by ajnyga** [comment]
I mean, I think that this whole section is actually not connected to payments at all:
https://github.com/pkp/ojs/blob/master/templates/payments/subscriptionPolicyForm.tpl#L70-L82

Besides giving the length of the embargo, journals do want to fill in for example the Author Self-Archiving Policy without enabling payments.

**Comment by asmecher** [comment]
Yes, please do!

**Comment by ajnyga** [comment]
@asmecher 
Self-archiving policy settings: https://github.com/pkp/ojs/pull/1880

**Pull request merged**
