### PR TITLE
pkp/pkp-lib#4246 Add option to select reviewers from last round

### PR DESCRIPTION
**Pull request by NateWr**

### CODE REVIEW

**Comment by Vitaliy-1** [comment]
@NateWr, it looks like this submodule update broke tests.

**Comment by asmecher** [comment]
^ yep, here's a temporary work-around for pkp-lib:
```diff
diff --git a/cypress/support/commands.js b/cypress/support/commands.js
index 02464a43f..137c68f41 100644
--- a/cypress/support/commands.js
+++ b/cypress/support/commands.js
@@ -458,7 +458,7 @@ Cypress.Commands.add('checkEmailTemplateVariables', (selector) => {
  * @param string selector An HTML element selector for a parent element that contains the email composer to check
  */
 Cypress.Commands.add('waitForEmailTemplateToBeLoaded', (selector) => {
-	cy.get(selector);
+	cy.wait(4000); // FIXME: Should be `cy.get(selector);` but the selector is currently missing
 	cy.get(selector + ' .composer__loadingTemplateMask').should('not.exist');
 });
 ```

**Comment by Vitaliy-1** [comment]
Problems I'm experiencing so far:

- Element with id `notifyAuthors` is missing: https://github.com/pkp/pkp-lib/blob/01303a10c72feabb225c658d16119381e34745fb/cypress/support/commands.js#L305-L306
- Instead of `button` element, there is element with a class `.pkpButton`, which contains `View Submission`: https://github.com/pkp/pkp-lib/blob/01303a10c72feabb225c658d16119381e34745fb/cypress/support/commands.js#L431
- When comparing dates here: https://github.com/pkp/pkp-lib/blob/01303a10c72feabb225c658d16119381e34745fb/cypress/support/commands.js#L614, extra space appears between a month and day if the latter has only one digit; this may be related to the recent date & time formatting switch from `strftime`:
```js
get div.pkpStatsgraph table tbody tr th:contains("January 29, 2022")
log January 29, 2022
get div.pkpStatsgraph table tbody tr th:contains("January 30, 2022")
log January 30, 2022
get div.pkpStatsgraph table tbody tr th:contains("January 31, 2022")
log January 31, 2022
get div.pkpStatsgraph table tbody tr th:contains("February  1, 2022")
```

**Comment by NateWr** [comment]
Are these test failures happening on Travis or just locally? The [tests passed](https://app.travis-ci.com/github/pkp/ojs/builds/248043808) on this PR before I merged.

**Comment by Vitaliy-1** [comment]
Yes, and it's weird. According to the commit history, they are failing after this commit: https://github.com/pkp/ojs/commit/27933b0ba247864836a9c14ea7598a3d5ab272be, e.g.: https://app.travis-ci.com/github/pkp/ojs/jobs/563738700 and I can reproduce it locally.

**Comment by NateWr** [comment]
I see the problem. Working on a fix now: https://github.com/pkp/pkp-lib/issues/7768#issuecomment-1073745361

**Comment by asmecher** [comment]
> When comparing dates here: https://github.com/pkp/pkp-lib/blob/01303a10c72feabb225c658d16119381e34745fb/cypress/support/commands.js#L614, extra space appears between a month and day if the latter has only one digit; this may be related to the recent date & time formatting switch from strftime:
> ```
> get div.pkpStatsgraph table tbody tr th:contains("January 29, 2022")
> log January 29, 2022
> get div.pkpStatsgraph table tbody tr th:contains("January 30, 2022")
> log January 30, 2022
> get div.pkpStatsgraph table tbody tr th:contains("January 31, 2022")
> log January 31, 2022
> get div.pkpStatsgraph table tbody tr th:contains("February  1, 2022")
> ```
This was actually due to a work-around for a problem that went away with the move from `strftime` (which space-padded single digit day numbers) to `date` (which doesn't). I have removed the work-around and the tests work locally; I'll watch the Travis tests to make sure. Commit: https://github.com/pkp/pkp-lib/commit/1a0f3c56b18c2c345179419c03c66a5fcc8b6748

**Pull request merged**
