### PR TITLE
Medra DOI automatic registration

### PR DESCRIPTION
**Pull request by marchitelli**
This is a tentative to port Automatic DOI registration to DataCite #594 to mEDRA registration plugin.

I have no more errors in my log but the articles are still unregistered. I tested the manual registration and it was ok, so the journal/doi/plugin configuration is ok.

On the journal the acron plugin is enabled and scheduled_task on config.inc.php are set to on
In the database the new setting is registered
"medraexportplugin";"''";30;"automaticRegistration";"1";"bool"

@bozana may you help me?

Thanks,
andrea

### CODE REVIEW

**Comment by bozana** [comment]
I'll take a look...

**Comment by bozana** [comment]
@marchitelli, I corrected some errors, s. this commit: https://github.com/bozana/ojs/commit/5947eea9bcbe696ea57c6c10093c6308cf19b87b
Could you take the commit and test it? If OK, you could push it to your repository anew and I will have a quick final look and merge it...
I am wondering that Datacite automatic registration worked at all :-P -- I will then have to correct it too...

**Comment by bozana** [comment]
@marchitelli, when you push the commit anew, could you please give it a message with the issue number above -- so we could track the issues and fixes -- i.e. something like: "pkp/pkp-lib#1543 Medra DOI automatic registration", ok?

**Comment by bozana** [comment]
@marchitelli, I've forgotten to say that I inserted a new locale key that you could eventually translate in Italian: plugins.importexport.medra.senderTask.warning.noDOIprefix

**Comment by marchitelli** [comment]
closing and reopening a different one

**Pull request closed without merging**
