### PR TITLE
pkp/pkp-lib#1754 OpenAIRE plugin migration

### PR DESCRIPTION
**Pull request by bozana**
S. https://github.com/pkp/pkp-lib/issues/1754
This makes the current OpenAIRE plugin work in OJS 3.0, thus maybe to integrate it?

### CODE REVIEW

**Comment by NateWr** [comment]
It looks like the tests just crapped out on you... :(

**Comment by bozana** [comment]
Yes :-((( :-D

**Comment by bozana** [comment]
@NateWr, I added the project id description as you suggested, s. the last commit above...

**Comment by NateWr** [comment]
Looks great @bozana! I think this needs a rebase and then it's ready to go. :tada:

**Comment by bozana** [comment]
OK, rebased and all tests are OK, so it can be merged and closed... :-)

**Comment by asmecher** [comment]
You won't have to tell me twice :)

**Pull request merged**
