### PR TITLE
Help panel scaffold

### PR DESCRIPTION
**Pull request by NateWr**

### CODE REVIEW

**Comment by NateWr** [comment]
Ugh, I must have done something wrong here. Tried to follow the steps to get the Travis CI testing working, but seem to have caused a merge conflict? Any idea what I'm meant to do here @asmecher?

**Comment by asmecher** [comment]
Nate, you'll need to do a rebase. It's probably a commit with an upstream submodule update or something. Want me to walk you through it via a hangout?

**Comment by NateWr** [comment]
Took another crack at this today, still no luck. Let's walk through it when I'm back in Edinburgh next week.

**Comment by NateWr** [comment]
I tried to rebase this today and `pkp-lib` seemed to work. But my `ojs` branch is all borked. It's just one tiny commit there, so I'll just start a new branch off current master and issue a new PR from that.

**Pull request closed without merging**
