### PR TITLE
Convert some docs into markdown

### PR DESCRIPTION
**Pull request by zuphilip**
Discussed in #2002.

### CODE REVIEW

**Comment by mtub** [comment]
I like this. If we don't just want to rely on GitHub rendering, maybe also transform the external links? Like  "https://github.com/pkp/pkp-lib#issues" etc. in REPORTING-BUGS.md - although this will make reading the raw file without any rendering a little more difficult. I'd still go with putting the links in there…

**Comment by zuphilip** [comment]
Are relative links only working in GitHub? Relative links work also for different branches, but maybe this is not a common scenario... I can do either way.

**Comment by asmecher** [comment]
Thanks, @zuphilip, and this is pretty uninvasive for non-github users. Merging now, but for extra bonus points, can you make the equivalent change in the OMP repository?

**Comment by zuphilip** [comment]
@asmecher Okay, I can also look for the other files in `doc` here first and then switch to OMP for the extra points :sparkles: .

**Comment by asmecher** [comment]
That would be fantastic, thanks!

**Pull request merged**
