### PR TITLE
MathJax plugin

### PR DESCRIPTION
**Pull request by vasylOstrovskyi**
Trivial MathJax plugin renders math in $LaTeX$ format. Just insers a few lines of JS into header.

### CODE REVIEW

**Comment by asmecher** [comment]
@vasylOstrovskyi, excellent work so far --

When you're ready for a code review, please let me know via a comment here.

Would you be willing to move this plugin into its own repository, rather than including it with the OJS repository? We're doing this with more and more of our own plugins, in part to decrease the number of plugins that ship with OJS (there are too many!) and in part to help foster an ecosystem of third-party plugins. See https://github.com/pkp/piwik for an example of a stand-alone plugin repository. (If you have changes to suggest to the main OJS repository as well, you'd need of course to send in a separate pull request for thise.)

**Comment by vasylOstrovskyi** [comment]
@asmecher, the code is ready for use now. I agree that it is a good idea to put this plugin into its own repository.  Unfortunately, I am new to github and do not know how to do that, Could you give me a hint?

**Comment by asmecher** [comment]
@vasylOstrovskyi, yes, you'd create a new repository in your account (the "+" in the top right of the git website). Then you'd clone it on your local machine, copy your plugin's files into it, `git add` them, `git commit` them, then `git push` them.

**Comment by vasylOstrovskyi** [comment]
Done, copied to [https://github.com/vasylOstrovskyi/mathJax](https://github.com/vasylOstrovskyi/mathJax).
Need another pull request? How to indicate that this must be used as a plugin submodule to OJS (add to plugin gallery)?

**Comment by asmecher** [comment]
@vasylOstrovskyi, I'll review that and create issues for whatever suggestions I have. Then, when we're finished, let me know and I'll walk you through wrapping it up for inclusion in the plugin gallery.

Closing this PR for now, I'll continue on your repo!

**Pull request closed without merging**
