### PR TITLE
Reference linking stable 3 1 2

### PR DESCRIPTION
**Pull request by bozana**
new crossref deposit api

### CODE REVIEW

**Comment by bozana** [comment]
Always a different test fails :-P Thus I will now merge this, and hope to see later what is going with the tests... :-\

**Comment by asmecher** [comment]
@bozana, I've noticed Travis failing more often recently -- I don't think it's a change on our part. However, you can restart individual jobs via Travis (it's a little more reliable than rolling 6 dice and hoping for the same result :)

**Comment by ctgraham** [comment]
@bozana, this leaves the production constants pointing to the test APIs.  Is this intended?
https://github.com/pkp/ojs/pull/2249/files#diff-3d6a2901be051c2b5d25cdb4ded5c438R25
https://github.com/pkp/ojs/pull/2249/files#diff-3d6a2901be051c2b5d25cdb4ded5c438R30

**Comment by bozana** [comment]
Ah, good catch @ctgraham! Phew... :+1:

**Pull request merged**
