### PR TITLE
Proxy support for DataVerse

### PR DESCRIPTION
**Pull request by Commifreak**
DataVerse plugin does not support proxy right now. Now it does.

Can someone review this and include this maybe? :)

### CODE REVIEW

**Comment by axfelix** [comment]
Looks fine to me -- although is it hardcoded to an HTTP and not an HTTPS proxy?

**Comment by Commifreak** [comment]
Dont know. I got this from an internal code from ojs/pkp. I dont know how the Config class is working. Is the third param a fallback value?

Please adapt it if needed :)

Gruß,
R. Kluth

**Comment by Commifreak** [comment]
Yep - 3rd parameter is default value, so there is no hardcoded http-pnly thing. If you mean that.

http_proxy contains only the proxy IP address. Curl does the rest.

I think the code is ok 👍

**Comment by axfelix** [comment]
OK -- haven't had the chance to test as I don't have a suitable proxy setup, but given that the implementation is identical to https://github.com/pkp/ojs/blob/1394d9d4db192bc85ea97fe9f4cea2afdfb71672/plugins/importexport/datacite/DataciteExportPlugin.inc.php and reported as working, I'm merging this. Thanks for the contribution!

**Comment by Commifreak** [comment]
Exactly :)

Thanks ;)

Gruß,
R. Kluth

**Pull request merged**
