### PR TITLE
pkp/pkp-lib#1772 Add required and aria-required attributes to form fields

### PR DESCRIPTION
**Pull request by NateWr**

### CODE REVIEW

**Comment by NateWr** [comment]
@asmecher or @bozana do you have any idea what causes these kinds of conflicts with a PR? There's no conflict reported for [pkp-lib](https://github.com/pkp/pkp-lib/pull/1942) or for the comparable PR for [omp](https://github.com/pkp/omp/pull/345). I tried using the command line to merge this PR with master locally, expecting to see some conflicts. But it merged cleanly. I'm not sure where to look next.

**Comment by bozana** [comment]
Hmmm... It seems like the OJS link to that submodule changed in the meanwhile... but I am not sure. You could try to remove the last commit (submodule update) and then rebase pkp-lib and ojs, and then add the new submodule update commit.

**Comment by NateWr** [comment]
That's what I've done over and over again. I'll try completely deleting my copy of `pkp-lib` locally and pulling fresh from my github repo...

**Comment by NateWr** [comment]
Hmm, yeah I just pulled `pkp-lib` fresh from `NateWr:master` but still getting the conflict. :/

**Comment by bozana** [comment]
I could maybe try to see...

**Comment by bozana** [comment]
hmm... s. https://github.com/pkp/ojs/pull/1155 -- I at least do not have those conflicts. I rebased the pkp-lib as well... So lets wait for tests, if OK, I can merge it, also for OMP... Is this ready to be merged?

**Comment by NateWr** [comment]
@bozana Thanks! Weird, I wonder what's going on. I don't think the tests have ever fully run, so maybe a good idea to see what happens with your PR tests first. But then it should be good to merge if the tests pass.

**Comment by bozana** [comment]
closing, s. https://github.com/pkp/ojs/pull/1155

**Pull request closed without merging**
