### PR TITLE
Help panel scaffold retry

### PR DESCRIPTION
**Pull request by NateWr**
Most of the changes are in a [this PR](https://github.com/pkp/pkp-lib/pull/811) for `pkp-lib`.

### CODE REVIEW

**Comment by asmecher** [comment]
@NateWr, you can see the JSLint errors for this PR here:
https://travis-ci.org/pkp/ojs/jobs/84909754

**Comment by NateWr** [comment]
@asmecher I fixed the first warning (hopefully), but not sure what to do about the other two.

[WARNING - Property off never defind on jQueryObject](https://travis-ci.org/pkp/ojs/jobs/84909754#L852). But jQuery objects do have an `off` function. Do I need to annotate this somehow?

[WARNING - actual parameter 1 of jQueryObject.prototype.is does not match formal parameter](https://travis-ci.org/pkp/ojs/jobs/84909754#L856) - so what exactly is the right approach here? `event.target` represents an EventTarget object which has all the details jQuery needs to make the comparison requested by `.is()`. I reckon I can do `$element.is( $(event.target) )` but I'm not sure what's better about that. It actually seems like it would be less performant, though I don't know for sure.

**Comment by asmecher** [comment]
@NateWr, we use a slightly-modified list of closure compiler externs that tell the closure compiler about the JQuery library functions; see `lib/pkp/tools/jquery-externs.js`. Looks like `.off` isn't included. I think the description of `.is` is probably incomplete there too.

There is a newer version of the externs file at https://github.com/google/closure-compiler/blob/master/contrib/externs/jquery-1.9.js but it looks like it'll take some work before we can replace the current version. I'd suggest extending the existing description in the current externs file for the moment.

**Comment by NateWr** [comment]
@asmecher Ok, I added `.off` and updated the `.is` definition. I think I did it right, copying the definitions over from the newer externs file and updating `jQuery` to `jQueryObject` in a couple places.

**Comment by asmecher** [comment]
It doesn't look like Travis testing re-ran and the PR is showing merge conflicts; mind seeing if you can get that going? Catch me tomorrow AM if you'd like a hand.

**Comment by NateWr** [comment]
Not sure what the trick is to get Travis running. All I know to do is the `Submodule update` trick, but I don't have any new commits for the `pkp-lib:help_panel_scaffold` branch....

**Comment by asmecher** [comment]
I think you need to do a...

    git rebase -i official/master

...and collapse all those submodule updates into one by making them "fixup" commits. It'll complain during the rebase because the official lib/pkp hash has changed, but if you...

    git add lib/pkp
    git rebase --continue

...you should be OK.

Travis testing should run on any application repo pull requests (omp and ojs, but not lib-pkp) automatically; I suspect that's not happening because of the conflict problem.

**Comment by NateWr** [comment]
`git add lib/pkp` got me past the first merge conflict, but got hung up on the second one. Since this only entails a one-line change in `ojs`, I'm just going to create a new branch off `official/master` and re-do the PR.

Here's my console output if in case we need to come back to this PR.

```
nate@nate-desktop:/var/www/html/ojs$ git rebase -i upstream/master
warning: Failed to merge submodule lib/pkp (merge following commits not found)
error: could not apply 80d0675... Submodule update ##NateWr/help_panel_scaffold##

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Could not apply 80d0675b8c13899a3f188a539ba48096d140e975... Submodule update ##NateWr/help_panel_scaffold##

nate@nate-desktop:/var/www/html/ojs$ git add lib/pkp
nate@nate-desktop:/var/www/html/ojs$ git rebase --continue
[detached HEAD a0f7a9e] Add new help panel controller to minified scripts
 2 files changed, 2 insertions(+), 1 deletion(-)
warning: Failed to merge submodule lib/pkp (commits don't follow merge-base)
error: could not apply e6aeb5d... Submodule update ##NateWr/help_panel_scaffold##

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Could not apply e6aeb5d862a06eee6d01b239c93c7dd072322e00... Submodule update ##NateWr/help_panel_scaffold##

nate@nate-desktop:/var/www/html/ojs$ git add lib/pkp
nate@nate-desktop:/var/www/html/ojs$ git rebase --continue
warning: Failed to merge submodule lib/pkp (commits don't follow merge-base)
error: could not apply cfc534b... Submodule update ##NateWr/help_panel_scaffold##

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Could not apply cfc534b18ada51d408041ffe21c8b806eb82f27d... Submodule update ##NateWr/help_panel_scaffold##
```

**Pull request closed without merging**
