### PR TITLE
Allow installations to limit the creation of session cookies to logged in users

### PR DESCRIPTION
**Pull request by ajnyga**
@asmecher @jmacgreg (@NateWr as well while you have been dealing with GDPR as well...)

Part of the GDPR changes in OJS: https://github.com/pkp/pkp-lib/issues/3624

Details:
- new `session_limit` setting in config.inc.php
- language settings are now stored to separate cookie, not in the session data. This cookie does not require consent, because it contains no personal data
- if `session_limit` is turned `On` sessions cookies are not created for users that are not logged in
- when goes to the login form, consent is asked for the privacy policy. The field is required for logging in. The privacy policy should of course mention the cookies.
- after user is logged in, a new `allowCookies` cookie is created (1 year), when the cookie exists, a session is created for the user
- when user logs out and returns, the login form will not show the consent checkbox anymore as long as the `allowCookies` exists.
- the IP in the session is always stored in encrypted form

### CODE REVIEW

**Comment by ajnyga** [comment]
Thanks, I got that commit message from here: https://pkp.sfu.ca/wiki/index.php?title=Information_for_Developers#PKP_library_submodule_changes

I will try again with the one you suggested later today.

About the changes above, yes it makes modifications to the login template. If you come up with an alternative way, let me know.

**Comment by ajnyga** [comment]
... not sure what version this is planned for...

**Comment by ajnyga** [comment]
this test failed in the same stage as the last one. Realized that the tests probably need the node.js and composer dependencies, right?

**Comment by NateWr** [comment]
The test runner will fetch the node/composer dependencies.

It looks like the tests are failing on a syntax error: https://travis-ci.org/pkp/ojs/jobs/390832925#L1166

**Comment by ajnyga** [comment]
thanks, I was just staring at the red line there and could not figure out what it means...

**Comment by ajnyga** [comment]
I can't make the submodule update work anymore. I do changes to the pkp/lib sessionmanager file and then try to git add lib/pkp but nothing is getting staged. I am using 80% of the time trying to figure out how to use git, which is a bit frustrating.

**Pull request closed without merging**
