### PR TITLE
[OJS] Pkp/pkp-lib#2064 standardize emailed url handling conflict2

### PR DESCRIPTION
**Pull request by defstat**

### CODE REVIEW

**Comment by defstat** [comment]
@asmecher the JS errors should be on validation checks? Right? It seems to pass those checks.

**Comment by asmecher** [comment]
I get...

    Compile (Check)...
	/tmp/tmp.cwAwCENOEj/lib/pkp/js/classes/TinyMCEHelper.js:98: ERROR - Parse error. missing } after function body
	/** @param {jQuery} $ jQuery closure. */
	
	1 error(s), 0 warning(s)

Have you rebased the `ojs` repo in your PR? I suspect it's still not linting everything; I introduced a change yesterday that should cause everything to get linted.

**Comment by defstat** [comment]
Well I git fetch upstream, git pull upstream master,  made a new branch from the master and cherry picked the changes from the old branch. And made a new PR of the newly created branch. I will try again.

**Comment by defstat** [comment]
@asmecher this time I git fetched upstream, git pull upstream master and rebased the working branch on the master branch. The checks started again, but the validations still pass for some reason. [the Compile (Check)... portion of the checks show nothing.]

**Comment by asmecher** [comment]
Replaced by https://github.com/pkp/ojs/pull/1336

**Pull request closed without merging**
