### PR TITLE
pkp/pkp-lib#4556 Submodule update ##ajnyga/f4556##

### PR DESCRIPTION
**Pull request by ajnyga**
https://github.com/pkp/pkp-lib/issues/4556

### CODE REVIEW

**Comment by ajnyga** [comment]
https://www.youtube.com/watch?v=DSlSaGcc0QM&feature=youtu.be&t=80

**Comment by NateWr** [comment]
🎶 I've made up my mind...  I aint wastin' no more 🎶 -- oh the tests passed.

**Comment by asmecher** [comment]
That video is blocked in Canada, but given that I can still read the title, it's a mercy.

**Comment by ajnyga** [comment]
Is 80s rock banned in Canada?

**Pull request closed without merging**
