### PR TITLE
pkp/pkp-lib#2461: Add section_ref as required attribute to articles; improve error recovery for native import when objects cannot be added to the database due to foreign key constraints

### PR DESCRIPTION
**Pull request by ctgraham**
Resolves pkp/pkp-lib#2461 in combination with pkp/pkp-lib#2522.

### CODE REVIEW

**Comment by bozana** [comment]
I will close and reopen the PR, to see if the tests will pass then -- Alec fixed them, I believe...
Else, all fine, can be merged...

**Comment by ctgraham** [comment]
Re-committed and force pushed branch to trigger tests, not that the tests do anything for the import/export plugin.  I'm pretty sure one existing test is invalid.

**Comment by bozana** [comment]
ah, I believe the import test is failing for real :-) I can test it locally ...

**Comment by bozana** [comment]
ok, I think that a rebase should solve the problem. @ctgraham, could you please rebase with pkp master and push -f again? THANSK!!!

**Comment by ctgraham** [comment]
Really?

In the testissue.xml, the `issue` [contains a `section`](https://github.com/pkp/ojs/blob/9aea082ead625d7702e868b657ef13d978f2d338/plugins/importexport/native/tests/functional/testissue.xml#L13) which [contains an `article`](https://github.com/pkp/ojs/blob/9aea082ead625d7702e868b657ef13d978f2d338/plugins/importexport/native/tests/functional/testissue.xml#L16).

Neither of these is allowed in the schema, to my reading.  The element [`section` has no `article` or `articles`](https://github.com/pkp/ojs/blob/9aea082ead625d7702e868b657ef13d978f2d338/plugins/importexport/native/native.xsd#L198-L215).  The element [`issue` has `sections` but not `section`](https://github.com/pkp/ojs/blob/9aea082ead625d7702e868b657ef13d978f2d338/plugins/importexport/native/native.xsd#L109-L129).

I can't imagine these tests having worked in any recent memory.  Am I misreading this?

**Comment by ctgraham** [comment]
Ahhh!  File `plugins/importexport/native/tests/functional/testissue.xml` isn't even used!  The running test is using `tests/data/60-content/issue.xml` !

**Comment by bozana** [comment]
The only think I can now imagine is the problem is, that the reference to lib/pkp is not up-to-date. I started a new PR for that here: https://github.com/pkp/ojs/pull/1387. If those tests pass, you would need to rebase and push -f again, sorry :-( Because, I do not think that any of the changes here causes any problem...

**Comment by ctgraham** [comment]
I tried adding the explicit reference to ##pkp/master## to ensure this commit was tested against the latest commits in the shared library, but it looks like startSubmodulesTRAVIS.sh didn't pick that up.
```
$ ./tools/startSubmodulesTRAVIS.sh

1 - Retrieving git user:

    Gituser: pkp

2 - Verifying if we have a merge commit in HEAD:

    Merge commit message: 1de180eedc4ad64fd1984df12cf75b0b97926c96 Merge 4f57fa3839d234d99282c6108da61bfdd97488eb into 9aea082ead625d7702e868b657ef13d978f2d338

    HEAD points to a merge commit.

    HEAD^ points to a common commit with hash 4f57fa3839d234d99282c6108da61bfdd97488eb

3 - Verifying if last non merge commit is a subproject commit:

    Subproject commit hash: 
```
Will force push again after https://github.com/pkp/ojs/pull/1387

**Comment by bozana** [comment]
@ctgraham, the other PR passed and I merged it. Could you then please rebase and force push again? And if that does not help, I will run the tests locally... :-)

**Comment by bozana** [comment]
OK, now it looks much better :-) Now a few times close and reopen the PR and it will be all green :-DDD :-)

**Pull request merged**
