### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by pnault**
Hi,

This is for version 3.1 coming for July.
Unable to remove old commits from PR.  I don't understand why they are still here. If someone could bring any light on this...
The last commit (8eeb8e2) is the good one.

Pierre

### CODE REVIEW

**Comment by asmecher** [comment]
@pnault, try an interactive rebase to remove any unwanted commits -- but beware that this is an easy way to nuke changes you wanted to keep, so make a copy of the files you've worked on before you do that!

**Comment by mtub** [comment]
Hi @pnault , if it's only that commit and these 5 files you want to keep, you could also start from an up-to-date master branch and cherry-pick your own commit from the other branch. There are conflicts for two files because the fr_CA files had been changed since you fetched and updated them, but they should be easily resolvable. Please let me know if you want me to commit these files for you - I could upload them and let you have a look before merging them.

**Comment by pnault** [comment]
Hi @mtub , I'm not sure to understand the cherry-picking thing. I didn't update my repo since 3.0.1. Please do commit these files for me. I will have a look before merging them.
thanks,

**Comment by pnault** [comment]
Hi @mtub , I'm not sure to understand the cherry-picking thing. I didn't update my repo since 3.0.1. Please do commit these files for me. I will have a look before merging them.
thanks,

**Comment by pnault** [comment]
Oups! reopening this PR.

**Comment by mtub** [comment]
superseded by #1436

**Pull request closed without merging**
