### PR TITLE
Update emailTemplates.xml fi_FI

### PR DESCRIPTION
**Pull request by ajnyga**
Small correction to editor recommendation template in fi_FI

@mtub (still waiting for a comment from my organisation regarding the CLA...)

### CODE REVIEW

**Comment by mtub** [comment]
@ajnyga , if you could sign the CLA, I'd be happy to merge this…

**Comment by ajnyga** [comment]
I have, about two weeks ago.

hmm...

**Comment by ajnyga** [comment]
ok, so I had to manually recheck the CLA in this pr.

**Comment by mtub** [comment]
I think you have to do this once for every repository you contribute to… :-|

Thanks!

**Comment by asmecher** [comment]
I set up the CLAs through the CLA Assistant to be linked, so it shouldn't be necessary to sign it once for every repo. When I made that change I think it discarded the signatures we already had, though...

**Pull request merged**
