### PR TITLE
Remove special characters from acronym when used in DOI suffix

### PR DESCRIPTION
**Pull request by ajnyga**
https://github.com/pkp/pkp-lib/issues/5505

### CODE REVIEW

**Comment by ajnyga** [comment]
@asmecher only one test failed and fairly late, do you wan to restart?

**Comment by NateWr** [comment]
Restarted the last test

**Comment by asmecher** [comment]
I'll look into the occasional failures when I get a sec. (I've seen one failure mode that's something deeply infrastructural and might require patience, and another one or two that might be races needing a delay during the testing.)

**Comment by asmecher** [comment]
The regexp looks fine to me!

**Comment by NateWr** [comment]
Committed in https://github.com/pkp/ojs/commit/3de15f4ceccaf598c785e75577a6e6b78bba984f

**Pull request closed without merging**
