### PR TITLE
Some pt localization

### PR DESCRIPTION
**Pull request by ambs**
Added some localization texts. Is this the best way to submit them?

### CODE REVIEW

**Comment by asmecher** [comment]
Yes, this is a good way to submit them, thanks! Note that the Travis tests have failed on a validation problem -- see https://travis-ci.org/pkp/ojs/jobs/364618905 for details. (I suspect the translator plugin created new XML with the wrong DTD path; check against the English files for the right path.) If you're handy with tools like Travis and can wade through the log file for the right content; feel free to fix them yourself; otherwise let me know and I'm happy to work on them as part of the merge process.

**Comment by ambs** [comment]
I will do it. Also, you can keep this open for future files. I decided to create the PR soon to guarantee not having two different persons working on the same task.

**Comment by asmecher** [comment]
Great, much appreciated! Just be sure to drop me a note when these are ready to be reviewed/merged.

**Comment by ambs** [comment]
All done. Waiting for Travis, to check which files need DTD corrections ;)

**Comment by asmecher** [comment]
Thanks! Merged and cherry-picked back to `ojs-stable-3_1_1`.

**Pull request merged**
