### PR TITLE
pkp/pkp-lib#6069 updated version in package-lock.json to 3.2.1

### PR DESCRIPTION
**Pull request by ViRuSTriNiTy**
see https://github.com/pkp/pkp-lib/issues/6069

### CODE REVIEW

**Comment by NateWr** [comment]
Thanks, can you update `package.json` as well? It should be 3.2.1 in `package.json` and then the value in `package-lock.json` is usually generated when `npm install` is run.

**Comment by ViRuSTriNiTy** [comment]
Sorry i'm not following. The file `package.json` already contains the correct version, see https://github.com/pkp/ojs/blob/stable-3_2_1/package.json

**Comment by NateWr** [comment]
My mistake! I didn't notice that this was against the `stable-3_2_1` branch. I was thinking of `master`, where it is still at `3.2.0`. My guess is that this is bumped by an automated script when Alec makes a build. I'll check with him, thanks for noticing this!

**Comment by asmecher** [comment]
Added a note about this in the release documentation (e.g. for OJS: https://github.com/pkp/ojs/commit/8fe51191840511144d22493b81abbf305547c48c)!

**Pull request merged**
