### PR TITLE
pkp/pkp-lib#2602 updated fr_CA locale

### PR DESCRIPTION
**Pull request by mtub**

### CODE REVIEW

**Comment by mtub** [comment]
@pnault , could you have a look?

I fetched your commit from https://github.com/pkp/ojs/pull/1436/commits/ab9b1dec356a530bc13e7748b027b0c17487391a, resolved the conflicts and uploaded everything. As soon as you tell me this is okay, we can proceed.

**Comment by pnault** [comment]
Hi @mtub . This look quite good! Sorry again for these unwanted commits/conflicts.
You can proceed.

**Comment by mtub** [comment]
No worries, conflicts are quite normal - code is always updated, and when the developers remove something or add something while you are translating, these things can happen.

**Comment by mtub** [comment]
self-merging now…

**Pull request merged**
